-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "togc"
local chunkStartIndex = 5183
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["katirokkt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5012, 130, 415, 2290 }
	end
end
do
	local player = players["jêylâ"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8169, 54, 153, 3368 }
	end
end
do
	local player = players["nightward"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1687, 176, 691, 1882 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4376, 86, 251, 7544 }
	end
end
do
	local player = players["deathrob"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5313, 122, 390, 2353 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1586, 333, 1267, 3108 }
	end
end
do
	local player = players["agnors"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4594, 263, 889, 9005 }
	end
end
do
	local player = players["thelaa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1120, 183, 738, 1819 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4586, 264, 891, 8988 }
	end
end
do
	local player = players["decranus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1043, 188, 776, 1747 }
	end
end
do
	local player = players["goil"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 916, 195, 820, 1534 }
	end
end
do
	local player = players["raag"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6169, 103, 319, 2541 }
	end
end
do
	local player = players["synril"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5699, 114, 358, 2429 }
	end
end
do
	local player = players["hêphaistos"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6711, 91, 274, 2706 }
	end
end
do
	local player = players["alwaysdrunk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7157, 85, 237, 2848 }
	end
end
do
	local player = players["kesaja"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1069, 185, 757, 1790 }
	end
end
do
	local player = players["peddaaggro"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9012, 28, 83, 8335 }
	end
end
do
	local player = players["skulld"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1651, 177, 694, 1880 }
	end
end
do
	local player = players["yeve"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8325, 49, 140, 3534 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9748, 18, 33, 16811 }
	end
end
do
	local player = players["antiengél"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9708, 23, 38, 16714 }
	end
end
do
	local player = players["kuraikó"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7714, 29, 73, 11426 }
	end
end
do
	local player = players["miniyarak"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8190, 23, 58, 12426 }
	end
end
do
	local player = players["burry"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9397, 11, 20, 14317 }
	end
end
do
	local player = players["chèrrycoke"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5349, 59, 155, 9221 }
	end
end
do
	local player = players["hakuren"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5735, 113, 355, 2432 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5497, 195, 572, 10514 }
	end
end
do
	local player = players["krizzlor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5162, 64, 177, 8899 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4328, 279, 999, 8483 }
	end
end
do
	local player = players["deathbuck"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7145, 143, 363, 11838 }
	end
end
do
	local player = players["killerdk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7458, 78, 212, 2935 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7965, 113, 259, 12618 }
	end
end
do
	local player = players["gutespils"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4883, 239, 767, 9572 }
	end
end
do
	local player = players["tanukiyula"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8170, 106, 233, 12857 }
	end
end
do
	local player = players["larios"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3089, 327, 1238, 6054 }
	end
end
do
	local player = players["deepfried"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8541, 90, 186, 13377 }
	end
end
do
	local player = players["àppaxx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9125, 58, 112, 14720 }
	end
end
do
	local player = players["teysøn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2675, 169, 609, 1995 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9614, 32, 50, 16180 }
	end
end
do
	local player = players["sátøx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4908, 235, 754, 9620 }
	end
end
do
	local player = players["pwndxxq"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5115, 219, 672, 10026 }
	end
end
do
	local player = players["cahìra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9054, 62, 121, 14495 }
	end
end
do
	local player = players["insaneinside"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 944, 194, 815, 1581 }
	end
end
do
	local player = players["hirschhelles"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4166, 291, 1060, 8165 }
	end
end
do
	local player = players["ambitiouz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9913, 8, 12, 17877 }
	end
end
do
	local player = players["simplydreck"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8588, 88, 180, 13466 }
	end
end
do
	local player = players["krelsa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4698, 253, 837, 9209 }
	end
end
do
	local player = players["icas"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9132, 57, 111, 14746 }
	end
end
do
	local player = players["dârthârthâqs"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8249, 102, 223, 12944 }
	end
end
do
	local player = players["yiggyx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4908, 234, 753, 9620 }
	end
end
do
	local player = players["seleena"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9345, 45, 84, 15385 }
	end
end
do
	local player = players["zunny"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5590, 117, 367, 2398 }
	end
end
do
	local player = players["kaldedk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5379, 200, 587, 10446 }
	end
end
do
	local player = players["ôrf"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4012, 304, 1116, 7863 }
	end
end
do
	local player = players["harvêy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9685, 25, 41, 16620 }
	end
end
do
	local player = players["jäckfrost"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6017, 181, 506, 10889 }
	end
end
do
	local player = players["dereinzigste"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7776, 119, 283, 12488 }
	end
end
do
	local player = players["tentaro"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9330, 46, 86, 15332 }
	end
end
do
	local player = players["spown"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9763, 17, 31, 16819 }
	end
end
do
	local player = players["donkeykøng"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4876, 240, 772, 9558 }
	end
end
do
	local player = players["bozzix"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4178, 290, 1056, 8189 }
	end
end
do
	local player = players["amrasch"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9724, 21, 36, 16759 }
	end
end
do
	local player = players["hansdk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7675, 69, 194, 3053 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6909, 152, 393, 11597 }
	end
end
do
	local player = players["guzmek"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7011, 149, 380, 11677 }
	end
end
do
	local player = players["crooq"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4306, 281, 1009, 8441 }
	end
end
do
	local player = players["xaxaxa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5852, 187, 527, 10765 }
	end
end
do
	local player = players["háze"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4031, 302, 1109, 7902 }
	end
end
do
	local player = players["nótánk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4829, 242, 784, 9465 }
	end
end
do
	local player = players["hansdudu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9156, 49, 104, 14439 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3385, 111, 320, 5895 }
	end
end
do
	local player = players["muhrama"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5348, 220, 704, 9235 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3123, 114, 325, 5438 }
	end
end
do
	local player = players["erendar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6926, 139, 376, 11353 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5837, 45, 98, 12 }
	end
end
do
	local player = players["nostradamo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7016, 136, 365, 11467 }
	end
end
do
	local player = players["izumoo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7492, 119, 307, 11965 }
	end
end
do
	local player = players["plüschpøwer"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7885, 103, 259, 12545 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3398, 69, 157, 1 }
	end
end
do
	local player = players["kautz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9623, 31, 47, 15147 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7554, 30, 58, 67 }
	end
end
do
	local player = players["cowtabacco"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6177, 169, 471, 10665 }
	end
end
do
	local player = players["manbearchick"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5524, 210, 653, 9538 }
	end
end
do
	local player = players["francheska"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4655, 270, 907, 8037 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4840, 95, 260, 8428 }
	end
end
do
	local player = players["sarichen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6615, 147, 414, 11125 }
	end
end
do
	local player = players["æstralis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4704, 268, 896, 8123 }
	end
end
do
	local player = players["greedie"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5075, 236, 785, 8762 }
	end
end
do
	local player = players["riasgremory"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6754, 143, 397, 11238 }
	end
end
do
	local player = players["turnbull"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5946, 185, 537, 10267 }
	end
end
do
	local player = players["lasergecko"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5295, 227, 716, 9143 }
	end
end
do
	local player = players["muhlemaus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5858, 191, 562, 10115 }
	end
end
do
	local player = players["tralbert"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9098, 51, 111, 14314 }
	end
end
do
	local player = players["chicken"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6344, 162, 447, 10869 }
	end
end
do
	local player = players["kaergor"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5872, 187, 554, 10140 }
	end
end
do
	local player = players["erdenrufer"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8131, 93, 229, 12898 }
	end
end
do
	local player = players["gerukks"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4901, 255, 842, 8462 }
	end
end
do
	local player = players["pianopeter"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7516, 117, 304, 11996 }
	end
end
do
	local player = players["zidaine"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8631, 71, 168, 13686 }
	end
end
do
	local player = players["farmerarma"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2425, 321, 1205, 4188 }
	end
end
do
	local player = players["decanaar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4148, 294, 1001, 7162 }
	end
end
do
	local player = players["bärhoof"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5969, 183, 530, 10306 }
	end
end
do
	local player = players["kuhgelig"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4913, 253, 839, 8483 }
	end
end
do
	local player = players["bursting"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5334, 222, 707, 9209 }
	end
end
do
	local player = players["owltist"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9533, 35, 58, 14989 }
	end
end
do
	local player = players["gelenkstefan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8959, 57, 128, 14079 }
	end
end
do
	local player = players["drunir"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2850, 116, 334, 4963 }
	end
end
do
	local player = players["icystorm"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2718, 76, 176, 0 }
	end
end
do
	local player = players["fálkon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4847, 94, 259, 8440 }
	end
end
do
	local player = players["hüpo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5251, 79, 217, 9144 }
	end
end
do
	local player = players["driui"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9809, 6, 8, 15581 }
	end
end
do
	local player = players["katzalysator"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9537, 14, 18, 14529 }
	end
end
do
	local player = players["snusbot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3150, 113, 324, 5485 }
	end
end
do
	local player = players["khandira"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 194, 102, 231, 0 }
	end
end
do
	local player = players["theodes"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8155, 23, 44, 92 }
	end
end
do
	local player = players["nobuck"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6558, 118, 478, 10668 }
	end
end
do
	local player = players["puddingham"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9351, 39, 91, 16151 }
	end
end
do
	local player = players["kaldebier"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3633, 230, 1097, 7276 }
	end
end
do
	local player = players["heralanea"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4726, 167, 732, 9303 }
	end
end
do
	local player = players["çlaire"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5736, 141, 592, 10004 }
	end
end
do
	local player = players["tyraspanks"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4639, 168, 744, 9225 }
	end
end
do
	local player = players["spirithunter"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3993, 211, 984, 7996 }
	end
end
do
	local player = players["xarenia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3437, 240, 1145, 6884 }
	end
end
do
	local player = players["cändy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4304, 188, 877, 8620 }
	end
end
do
	local player = players["sunflare"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6118, 129, 539, 10278 }
	end
end
do
	local player = players["raytwo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6032, 132, 551, 10227 }
	end
end
do
	local player = players["shaarooñ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5281, 150, 655, 9682 }
	end
end
do
	local player = players["zeratuel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8268, 73, 241, 13882 }
	end
end
do
	local player = players["gorgblump"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4106, 206, 949, 8223 }
	end
end
do
	local player = players["rimny"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3910, 217, 1013, 7832 }
	end
end
do
	local player = players["packmas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6450, 123, 493, 10544 }
	end
end
do
	local player = players["kempes"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4589, 170, 751, 9188 }
	end
end
do
	local player = players["shinbalah"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3198, 249, 1208, 6406 }
	end
end
do
	local player = players["crazysteph"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8889, 56, 155, 15246 }
	end
end
do
	local player = players["firenzo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6566, 117, 477, 10681 }
	end
end
do
	local player = players["miiriia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9307, 43, 97, 16091 }
	end
end
do
	local player = players["philippqt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4474, 182, 806, 8959 }
	end
end
do
	local player = players["buniac"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2805, 256, 1270, 5619 }
	end
end
do
	local player = players["krazî"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3263, 247, 1191, 6535 }
	end
end
do
	local player = players["versprengt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7368, 8, 16, 12390 }
	end
end
do
	local player = players["argusmagus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6731, 18, 37, 11418 }
	end
end
do
	local player = players["blinkdings"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3774, 39, 70, 6749 }
	end
end
do
	local player = players["pewkrachbumm"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4753, 30, 55, 8498 }
	end
end
do
	local player = players["bennêlopè"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6235, 202, 620, 13061 }
	end
end
do
	local player = players["iordanov"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5112, 287, 1030, 11237 }
	end
end
do
	local player = players["croolfire"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6849, 175, 519, 13785 }
	end
end
do
	local player = players["kameehameeha"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7409, 155, 427, 14589 }
	end
end
do
	local player = players["antiwizzard"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5665, 230, 752, 12453 }
	end
end
do
	local player = players["leonârdo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4633, 332, 1230, 10184 }
	end
end
do
	local player = players["fizale"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9300, 69, 116, 17997 }
	end
end
do
	local player = players["magepewpew"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4699, 327, 1209, 10329 }
	end
end
do
	local player = players["avandur"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9355, 66, 107, 18096 }
	end
end
do
	local player = players["malunia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2614, 436, 1617, 5746 }
	end
end
do
	local player = players["nemartresa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7080, 165, 481, 14079 }
	end
end
do
	local player = players["firemagex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8133, 121, 308, 15872 }
	end
end
do
	local player = players["fussel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7457, 154, 419, 14690 }
	end
end
do
	local player = players["firebløød"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6887, 169, 501, 13837 }
	end
end
do
	local player = players["muezzin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3650, 41, 72, 6527 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6916, 172, 508, 13862 }
	end
end
do
	local player = players["daddydünsch"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6867, 174, 516, 13819 }
	end
end
do
	local player = players["dpscc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7603, 147, 395, 14896 }
	end
end
do
	local player = players["ayzora"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5210, 275, 982, 11453 }
	end
end
do
	local player = players["velsing"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4411, 349, 1299, 9697 }
	end
end
do
	local player = players["zunni"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9021, 87, 162, 17297 }
	end
end
do
	local player = players["keksmage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9434, 58, 94, 18265 }
	end
end
do
	local player = players["taikuri"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4394, 350, 1305, 9658 }
	end
end
do
	local player = players["nadili"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8875, 98, 186, 17057 }
	end
end
do
	local player = players["gerdie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5717, 223, 729, 12567 }
	end
end
do
	local player = players["ashwings"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6454, 190, 584, 13300 }
	end
end
do
	local player = players["wraji"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6703, 180, 543, 13571 }
	end
end
do
	local player = players["andorok"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8796, 100, 199, 17012 }
	end
end
do
	local player = players["floxus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5348, 260, 909, 11756 }
	end
end
do
	local player = players["uzax"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4865, 316, 1153, 10693 }
	end
end
do
	local player = players["donkarlsen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4989, 303, 1093, 10966 }
	end
end
do
	local player = players["zartbîtter"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5361, 259, 899, 11785 }
	end
end
do
	local player = players["flereigam"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8625, 106, 227, 16754 }
	end
end
do
	local player = players["noobí"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8242, 116, 290, 16090 }
	end
end
do
	local player = players["magequisit"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4013, 389, 1417, 8822 }
	end
end
do
	local player = players["alfón"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5711, 224, 732, 12553 }
	end
end
do
	local player = players["minichaot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7172, 161, 466, 14225 }
	end
end
do
	local player = players["softhorn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7841, 137, 356, 15307 }
	end
end
do
	local player = players["flaereon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7780, 139, 366, 15149 }
	end
end
do
	local player = players["ayabast"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4075, 380, 1398, 8957 }
	end
end
do
	local player = players["zøltun"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5175, 281, 1002, 11375 }
	end
end
do
	local player = players["semmelgottx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5564, 240, 800, 12230 }
	end
end
do
	local player = players["loighor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6052, 207, 650, 12928 }
	end
end
do
	local player = players["hëra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4576, 340, 1254, 10059 }
	end
end
do
	local player = players["dankesehr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5452, 251, 855, 11985 }
	end
end
do
	local player = players["madteiwaz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9416, 59, 97, 18227 }
	end
end
do
	local player = players["dáblex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4608, 163, 455, 197 }
	end
end
do
	local player = players["máriellà"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5843, 133, 351, 217 }
	end
end
do
	local player = players["comode"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9406, 28, 51, 355 }
	end
end
do
	local player = players["patzy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9026, 48, 83, 319 }
	end
end
do
	local player = players["nôrdic"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4430, 167, 470, 194 }
	end
end
do
	local player = players["regi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9917, 6, 8, 494 }
	end
end
do
	local player = players["shiexz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3646, 183, 536, 180 }
	end
end
do
	local player = players["divy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 821, 227, 791, 116 }
	end
end
do
	local player = players["atlantiqa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3670, 182, 534, 180 }
	end
end
do
	local player = players["olympîa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2601, 201, 624, 164 }
	end
end
do
	local player = players["holyshìt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4917, 151, 429, 201 }
	end
end
do
	local player = players["noomercya"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6639, 111, 284, 233 }
	end
end
do
	local player = players["dertankmk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4121, 172, 496, 188 }
	end
end
do
	local player = players["kivy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7518, 88, 210, 255 }
	end
end
do
	local player = players["belyon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2292, 205, 650, 160 }
	end
end
do
	local player = players["pixipie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3649, 185, 873, 2219 }
	end
end
do
	local player = players["zophy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3496, 188, 894, 1968 }
	end
end
do
	local player = players["juicyrich"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7480, 80, 347, 5120 }
	end
end
do
	local player = players["mustalentlos"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6793, 104, 271, 237 }
	end
end
do
	local player = players["tonibella"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2185, 212, 1074, 1100 }
	end
end
do
	local player = players["hólytánk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2542, 203, 629, 163 }
	end
end
do
	local player = players["protwal"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 1413, 228, 1180, 848 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4536, 324, 982, 8177 }
	end
end
do
	local player = players["zêùs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8755, 43, 172, 6613 }
	end
end
do
	local player = players["damaris"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1437, 211, 722, 145 }
	end
end
do
	local player = players["bombâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3372, 192, 911, 1756 }
	end
end
do
	local player = players["mäxlekäxle"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6869, 157, 399, 10871 }
	end
end
do
	local player = players["henrycake"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2581, 390, 1262, 4652 }
	end
end
do
	local player = players["bénihime"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7600, 126, 306, 11735 }
	end
end
do
	local player = players["bugshield"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9756, 24, 32, 16339 }
	end
end
do
	local player = players["tankpflaster"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6042, 196, 504, 10138 }
	end
end
do
	local player = players["wondérwoman"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6642, 110, 462, 4275 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4170, 349, 1099, 7516 }
	end
end
do
	local player = players["bérgen"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5246, 249, 673, 9456 }
	end
end
do
	local player = players["redshiva"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8363, 88, 209, 13286 }
	end
end
do
	local player = players["lûmiel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5641, 215, 555, 9910 }
	end
end
do
	local player = players["xäshistar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6773, 106, 444, 4424 }
	end
end
do
	local player = players["merogus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4905, 152, 430, 201 }
	end
end
do
	local player = players["zezilia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4707, 315, 923, 8485 }
	end
end
do
	local player = players["minaji"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7537, 131, 314, 11702 }
	end
end
do
	local player = players["masharu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6341, 186, 466, 10425 }
	end
end
do
	local player = players["frizzbox"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7708, 82, 194, 261 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9002, 37, 138, 7045 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3935, 362, 1158, 7093 }
	end
end
do
	local player = players["lothacân"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6585, 168, 435, 10614 }
	end
end
do
	local player = players["sleyér"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9501, 23, 43, 375 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8143, 100, 237, 12665 }
	end
end
do
	local player = players["kaleydo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1164, 214, 745, 138 }
	end
end
do
	local player = players["firelead"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6730, 108, 450, 4394 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4408, 337, 1027, 7946 }
	end
end
do
	local player = players["sêrwantes"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4735, 310, 914, 8536 }
	end
end
do
	local player = players["vaylyn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5110, 271, 742, 9212 }
	end
end
do
	local player = players["niggelsn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9630, 30, 48, 15871 }
	end
end
do
	local player = players["meteóra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6380, 119, 498, 4073 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3906, 366, 1164, 7041 }
	end
end
do
	local player = players["uhurah"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6723, 109, 451, 4380 }
	end
end
do
	local player = players["selaia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6019, 197, 507, 10130 }
	end
end
do
	local player = players["watschlicht"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9111, 33, 123, 7257 }
	end
end
do
	local player = players["rikary"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8990, 50, 86, 315 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8961, 60, 133, 14248 }
	end
end
do
	local player = players["cherrylâdy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2112, 215, 1084, 1075 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8419, 86, 202, 13406 }
	end
end
do
	local player = players["farodín"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7626, 75, 327, 5343 }
	end
end
do
	local player = players["kampfhering"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8316, 90, 215, 13238 }
	end
end
do
	local player = players["acidhâmmer"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7309, 146, 343, 11373 }
	end
end
do
	local player = players["tankeêeêeêeê"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3948, 177, 832, 2618 }
	end
end
do
	local player = players["scürty"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1045, 218, 755, 134 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5247, 247, 671, 9458 }
	end
end
do
	local player = players["raphaéla"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5007, 279, 787, 9026 }
	end
end
do
	local player = players["niggels"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5133, 266, 727, 9253 }
	end
end
do
	local player = players["rosaparks"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4625, 168, 739, 3093 }
	end
end
do
	local player = players["nemme"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8820, 71, 151, 13968 }
	end
end
do
	local player = players["qu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4792, 165, 716, 3159 }
	end
end
do
	local player = players["dingaria"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6530, 172, 442, 10589 }
	end
end
do
	local player = players["klexina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6533, 113, 477, 4205 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6357, 185, 464, 10439 }
	end
end
do
	local player = players["hippoterus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4836, 164, 710, 3177 }
	end
end
do
	local player = players["scurty"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4240, 169, 486, 190 }
	end
end
do
	local player = players["dartun"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5018, 278, 780, 9046 }
	end
end
do
	local player = players["kêito"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3875, 180, 842, 2513 }
	end
end
do
	local player = players["shutaras"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6526, 114, 478, 4200 }
	end
end
do
	local player = players["tyrâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6147, 130, 530, 3901 }
	end
end
do
	local player = players["rattig"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5649, 214, 554, 9923 }
	end
end
do
	local player = players["sadíst"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6900, 154, 395, 10898 }
	end
end
do
	local player = players["melnick"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6805, 103, 270, 237 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5058, 276, 769, 9117 }
	end
end
do
	local player = players["laylaylii"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9409, 26, 41, 366 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8038, 17, 32, 200 }
	end
end
do
	local player = players["kimaléria"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 207, 204, 664, 0 }
	end
end
do
	local player = players["dragonforce"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5908, 109, 278, 119 }
	end
end
do
	local player = players["inarizaki"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 414, 200, 650, 0 }
	end
end
do
	local player = players["heilererin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4476, 137, 375, 94 }
	end
end
do
	local player = players["tylliania"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6529, 98, 236, 140 }
	end
end
do
	local player = players["vantagex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9734, 13, 19, 710 }
	end
end
do
	local player = players["patre"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3604, 154, 434, 83 }
	end
end
do
	local player = players["mîrana"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4284, 139, 388, 91 }
	end
end
do
	local player = players["bowo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3678, 151, 429, 83 }
	end
end
do
	local player = players["lycanda"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3205, 160, 461, 77 }
	end
end
do
	local player = players["dërheal"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6115, 104, 264, 124 }
	end
end
do
	local player = players["shiomvor"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6366, 100, 247, 134 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6994, 156, 393, 11327 }
	end
end
do
	local player = players["losthopî"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6329, 34, 59, 125 }
	end
end
do
	local player = players["saíntanger"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 1392, 54, 137, 24 }
	end
end
do
	local player = players["xyrilla"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5633, 36, 70, 105 }
	end
end
do
	local player = players["schadenholy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3235, 159, 459, 78 }
	end
end
do
	local player = players["nunpi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7899, 123, 275, 12201 }
	end
end
do
	local player = players["blinkeypri"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3971, 289, 925, 7785 }
	end
end
do
	local player = players["bankirilla"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3713, 315, 1029, 7278 }
	end
end
do
	local player = players["papeos"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8351, 100, 216, 12617 }
	end
end
do
	local player = players["slimshieldy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9143, 33, 59, 282 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9003, 66, 131, 13851 }
	end
end
do
	local player = players["diggsia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5445, 197, 595, 9997 }
	end
end
do
	local player = players["lyneá"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9486, 38, 68, 15244 }
	end
end
do
	local player = players["undisturbed"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6894, 160, 406, 11214 }
	end
end
do
	local player = players["ayaní"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4180, 141, 395, 90 }
	end
end
do
	local player = players["amordeus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9557, 22, 31, 447 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5583, 191, 577, 10154 }
	end
end
do
	local player = players["lilamelialu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4484, 248, 756, 8790 }
	end
end
do
	local player = players["schlitzx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7446, 137, 334, 11810 }
	end
end
do
	local player = players["lernmalspüln"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7477, 136, 330, 11817 }
	end
end
do
	local player = players["noxinâ"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5307, 202, 613, 9870 }
	end
end
do
	local player = players["bæbyspeck"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9770, 18, 31, 16123 }
	end
end
do
	local player = players["priestilon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9187, 58, 107, 14635 }
	end
end
do
	local player = players["knottel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 399, 201, 651, 0 }
	end
end
do
	local player = players["fylax"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4003, 286, 916, 7847 }
	end
end
do
	local player = players["viti"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6948, 159, 399, 11293 }
	end
end
do
	local player = players["ibooz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2186, 177, 530, 61 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5637, 189, 570, 10210 }
	end
end
do
	local player = players["bagorini"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8700, 44, 89, 231 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6150, 178, 503, 10644 }
	end
end
do
	local player = players["senmeister"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6212, 176, 495, 10732 }
	end
end
do
	local player = players["caphalorus"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5859, 182, 541, 10377 }
	end
end
do
	local player = players["zinai"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3816, 300, 987, 7481 }
	end
end
do
	local player = players["shadowforcer"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3908, 294, 957, 7662 }
	end
end
do
	local player = players["fuqoff"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6534, 168, 453, 10961 }
	end
end
do
	local player = players["fîx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5377, 123, 314, 108 }
	end
end
do
	local player = players["nuctur"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9823, 9, 13, 1003 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6350, 173, 477, 10839 }
	end
end
do
	local player = players["sphay"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4038, 284, 902, 7917 }
	end
end
do
	local player = players["rubiná"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4694, 234, 706, 9203 }
	end
end
do
	local player = players["aalkaa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4760, 227, 686, 9332 }
	end
end
do
	local player = players["imery"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 1329, 55, 138, 17 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4169, 272, 852, 8174 }
	end
end
do
	local player = players["jìxxy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4736, 230, 694, 9285 }
	end
end
do
	local player = players["ayunei"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 74, 205, 673, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5721, 187, 559, 10251 }
	end
end
do
	local player = players["sabbatical"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5184, 206, 629, 9756 }
	end
end
do
	local player = players["prophetin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8014, 120, 260, 12270 }
	end
end
do
	local player = players["schildgecko"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4860, 131, 349, 99 }
	end
end
do
	local player = players["beautý"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4711, 232, 702, 9236 }
	end
end
do
	local player = players["aragôrn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1315, 188, 589, 24 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2329, 356, 1286, 4565 }
	end
end
do
	local player = players["heilgöttin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4061, 283, 897, 7961 }
	end
end
do
	local player = players["synnora"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8106, 116, 248, 12354 }
	end
end
do
	local player = players["kennyisdown"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 30, 206, 676, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9709, 24, 39, 15904 }
	end
end
do
	local player = players["valdawie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4763, 220, 963, 8800 }
	end
end
do
	local player = players["mîn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5140, 189, 760, 9497 }
	end
end
do
	local player = players["jænnedarc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4811, 213, 940, 8890 }
	end
end
do
	local player = players["orangejuiice"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5404, 162, 610, 9985 }
	end
end
do
	local player = players["crîtît"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3815, 253, 1204, 7050 }
	end
end
do
	local player = players["atstecher"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8172, 72, 231, 13128 }
	end
end
do
	local player = players["ømén"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5604, 153, 554, 10265 }
	end
end
do
	local player = players["asycs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3819, 252, 1201, 7056 }
	end
end
do
	local player = players["cuddey"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4011, 247, 1174, 7411 }
	end
end
do
	local player = players["ynorim"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6073, 137, 495, 10504 }
	end
end
do
	local player = players["mòjò"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4273, 240, 1132, 7894 }
	end
end
do
	local player = players["sneáky"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9825, 12, 23, 16519 }
	end
end
do
	local player = players["bergfresser"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8331, 65, 211, 13388 }
	end
end
do
	local player = players["summêr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5001, 201, 835, 9240 }
	end
end
do
	local player = players["becheftigt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7814, 84, 276, 12422 }
	end
end
do
	local player = players["soréanas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5731, 149, 538, 10321 }
	end
end
do
	local player = players["bongobernd"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8299, 67, 215, 13362 }
	end
end
do
	local player = players["bazzen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4765, 219, 961, 8805 }
	end
end
do
	local player = players["sockington"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4667, 224, 1005, 8622 }
	end
end
do
	local player = players["swirlý"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5085, 195, 798, 9395 }
	end
end
do
	local player = players["ziee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4880, 209, 899, 9016 }
	end
end
do
	local player = players["uhzi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4536, 224, 1022, 8382 }
	end
end
do
	local player = players["luthernîles"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3749, 255, 1211, 6927 }
	end
end
do
	local player = players["dav"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6439, 127, 449, 10765 }
	end
end
do
	local player = players["vøllbracht"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4607, 80, 265, 10009 }
	end
end
do
	local player = players["leafâa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4072, 100, 317, 8847 }
	end
end
do
	local player = players["atandios"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4005, 102, 321, 8702 }
	end
end
do
	local player = players["hêliøs"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 280, 279, 973, 0 }
	end
end
do
	local player = players["catahec"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4855, 74, 241, 10548 }
	end
end
do
	local player = players["yonaschama"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6071, 148, 390, 87 }
	end
end
do
	local player = players["weyz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5077, 67, 226, 11031 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 40, 286, 987, 0 }
	end
end
do
	local player = players["schamüsli"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2478, 122, 398, 5384 }
	end
end
do
	local player = players["vidaal"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8394, 72, 160, 382 }
	end
end
do
	local player = players["geblitzt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6171, 21, 36, 10049 }
	end
end
do
	local player = players["spellhance"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7676, 14, 20, 12498 }
	end
end
do
	local player = players["vollgaskastn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7848, 93, 214, 207 }
	end
end
do
	local player = players["islaearon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7273, 120, 271, 147 }
	end
end
do
	local player = players["selenna"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3657, 206, 629, 34 }
	end
end
do
	local player = players["zapfhan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5747, 158, 422, 78 }
	end
end
do
	local player = players["mfrog"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2758, 229, 718, 20 }
	end
end
do
	local player = players["nezuo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6747, 132, 323, 111 }
	end
end
do
	local player = players["ximto"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6242, 143, 373, 91 }
	end
end
do
	local player = players["heldenrausch"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 909, 261, 906, 0 }
	end
end
do
	local player = players["newoi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4273, 199, 568, 45 }
	end
end
do
	local player = players["dàrbee"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5677, 160, 429, 76 }
	end
end
do
	local player = players["shamin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2212, 238, 772, 12 }
	end
end
do
	local player = players["tömiis"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8333, 76, 166, 354 }
	end
end
do
	local player = players["babanouga"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5636, 161, 433, 75 }
	end
end
do
	local player = players["joulski"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7838, 94, 215, 206 }
	end
end
do
	local player = players["modge"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5465, 168, 450, 70 }
	end
end
do
	local player = players["tallahorn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1657, 247, 827, 4 }
	end
end
do
	local player = players["linil"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6606, 137, 337, 105 }
	end
end
do
	local player = players["shervin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2000, 241, 793, 9 }
	end
end
do
	local player = players["semegal"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7495, 108, 249, 156 }
	end
end
do
	local player = players["gorko"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7525, 106, 246, 159 }
	end
end
do
	local player = players["anajinn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6465, 138, 351, 97 }
	end
end
do
	local player = players["nemoi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5040, 180, 492, 61 }
	end
end
do
	local player = players["zypra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 594, 270, 946, 0 }
	end
end
do
	local player = players["meziege"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3131, 218, 681, 25 }
	end
end
do
	local player = players["nosdin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5348, 41, 83, 11002 }
	end
end
do
	local player = players["hexenhanzi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3385, 65, 132, 6964 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7771, 84, 188, 12317 }
	end
end
do
	local player = players["jackport"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5098, 149, 423, 9988 }
	end
end
do
	local player = players["benne"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5197, 145, 404, 10174 }
	end
end
do
	local player = players["dystroy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4695, 174, 499, 9198 }
	end
end
do
	local player = players["volupìa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5157, 148, 412, 10105 }
	end
end
do
	local player = players["sabodge"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3976, 224, 676, 7789 }
	end
end
do
	local player = players["demoness"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4642, 175, 511, 9095 }
	end
end
do
	local player = players["happysóul"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5983, 128, 338, 10811 }
	end
end
do
	local player = players["andromalíus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8605, 61, 118, 13760 }
	end
end
do
	local player = players["sleyër"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8474, 67, 129, 13617 }
	end
end
do
	local player = players["heidiheida"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3808, 230, 708, 7462 }
	end
end
do
	local player = players["morgâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4413, 190, 561, 8647 }
	end
end
do
	local player = players["mathildi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7318, 98, 226, 11910 }
	end
end
do
	local player = players["proudoflocks"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5809, 36, 72, 11950 }
	end
end
do
	local player = players["kamiol"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2872, 66, 137, 5909 }
	end
end
do
	local player = players["tassi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9046, 43, 81, 14607 }
	end
end
do
	local player = players["valeviah"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5316, 143, 394, 10240 }
	end
end
do
	local player = players["shadarr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5495, 139, 379, 10373 }
	end
end
do
	local player = players["miriandâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3581, 237, 740, 7017 }
	end
end
do
	local player = players["neós"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4028, 222, 665, 7891 }
	end
end
do
	local player = players["goldstoff"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4302, 198, 591, 8430 }
	end
end
do
	local player = players["lócksalot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4760, 170, 487, 9326 }
	end
end
do
	local player = players["orktoberfest"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5209, 144, 403, 10178 }
	end
end
do
	local player = players["nøs"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3104, 9, 13, 5189 }
	end
end
do
	local player = players["tschartsch"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4504, 22, 57, 8405 }
	end
end
do
	local player = players["glarin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8162, 146, 440, 17492 }
	end
end
do
	local player = players["kasarundaras"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9441, 58, 139, 22017 }
	end
end
do
	local player = players["marlun"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9076, 86, 229, 20798 }
	end
end
do
	local player = players["xardal"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8537, 125, 362, 18901 }
	end
end
do
	local player = players["bellicus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4047, 391, 1665, 11146 }
	end
end
do
	local player = players["bakis"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5956, 279, 999, 13775 }
	end
end
do
	local player = players["smashbro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9153, 79, 210, 20988 }
	end
end
do
	local player = players["chârgexløl"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4022, 393, 1681, 11078 }
	end
end
do
	local player = players["senfeier"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7472, 183, 625, 15962 }
	end
end
do
	local player = players["epçs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9283, 70, 178, 21468 }
	end
end
do
	local player = players["zedseroya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8152, 147, 444, 17492 }
	end
end
do
	local player = players["schadenwohr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3484, 441, 2113, 9595 }
	end
end
do
	local player = players["schnubine"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4363, 352, 1403, 12017 }
	end
end
do
	local player = players["ellywoodxy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5541, 51, 137, 2735 }
	end
end
do
	local player = players["chakra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7168, 204, 700, 15552 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8393, 20, 50, 4618 }
	end
end
do
	local player = players["missiwar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2839, 483, 2384, 7818 }
	end
end
do
	local player = players["nøvicron"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9327, 67, 167, 21681 }
	end
end
do
	local player = players["karâkan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8408, 132, 394, 18541 }
	end
end
do
	local player = players["metzker"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8886, 98, 276, 20052 }
	end
end
do
	local player = players["borondir"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2623, 65, 226, 560 }
	end
end
do
	local player = players["dingoosa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8225, 141, 439, 17859 }
	end
end
do
	local player = players["jîmmyfloyd"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8716, 110, 318, 19407 }
	end
end
do
	local player = players["wuttutmirgut"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7087, 209, 720, 15437 }
	end
end
do
	local player = players["cattafury"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9797, 25, 51, 23681 }
	end
end
do
	local player = players["pishro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8707, 112, 320, 19386 }
	end
end
do
	local player = players["lecksau"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3586, 434, 2040, 9876 }
	end
end
do
	local player = players["phemezzo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3287, 463, 2238, 9053 }
	end
end
do
	local player = players["grenski"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2295, 66, 236, 493 }
	end
end
do
	local player = players["aufräumer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3918, 407, 1778, 10790 }
	end
end
do
	local player = players["kassierer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5608, 298, 1085, 13393 }
	end
end
do
	local player = players["vulkyøh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4330, 356, 1431, 11924 }
	end
end
do
	local player = players["voodoocharge"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6896, 227, 767, 15116 }
	end
end
do
	local player = players["brôoky"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3895, 411, 1796, 10728 }
	end
end
do
	local player = players["puxy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6532, 245, 857, 14601 }
	end
end
do
	local player = players["ãrês"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6844, 233, 780, 15055 }
	end
end
do
	local player = players["nichtbozzi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6402, 250, 889, 14468 }
	end
end
do
	local player = players["blinkeykri"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6001, 276, 988, 13872 }
	end
end
do
	local player = players["xeywia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8181, 147, 450, 17687 }
	end
end
do
	local player = players["vâsh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7301, 195, 667, 15719 }
	end
end
do
	local player = players["wynna"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3741, 424, 1927, 10303 }
	end
end
do
	local player = players["ninase"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3489, 439, 2107, 9611 }
	end
end
do
	local player = players["mczaet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9133, 81, 215, 20923 }
	end
end
do
	local player = players["roadcleaver"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6244, 259, 928, 14245 }
	end
end
do
	local player = players["gønathira"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4903, 332, 1259, 12592 }
	end
end
do
	local player = players["kanonen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3967, 399, 1724, 10926 }
	end
end
do
	local player = players["camonme"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6110, 268, 961, 14054 }
	end
end
do
	local player = players["equìnôxx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5340, 306, 1151, 13059 }
	end
end
do
	local player = players["orifighter"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9838, 21, 41, 23938 }
	end
end
do
	local player = players["zarachie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8821, 102, 292, 19806 }
	end
end
do
	local player = players["jörgsaronn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5916, 281, 1009, 13734 }
	end
end
do
	local player = players["ellywòòd"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4250, 369, 1492, 11704 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6361, 36, 112, 3247 }
	end
end
do
	local player = players["lancee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7143, 207, 706, 15516 }
	end
end
do
	local player = players["risenhuman"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5113, 322, 1207, 12836 }
	end
end
do
	local player = players["ráyzor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6827, 234, 784, 15021 }
	end
end
do
	local player = players["laylaylaa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6876, 229, 772, 15090 }
	end
end
do
	local player = players["lòcknar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7062, 211, 726, 15391 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
