-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "togc"
local chunkStartIndex = 6841
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["dacarma"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4750, 134, 432, 2236 }
	end
end
do
	local player = players["aparollo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1010, 189, 789, 1692 }
	end
end
do
	local player = players["jornala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5457, 117, 374, 2368 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3239, 318, 1208, 6350 }
	end
end
do
	local player = players["kratosz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5907, 107, 337, 2481 }
	end
end
do
	local player = players["olchin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3362, 151, 546, 2045 }
	end
end
do
	local player = players["seuthe"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7856, 61, 177, 3143 }
	end
end
do
	local player = players["decran"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5116, 126, 402, 2311 }
	end
end
do
	local player = players["vaporized"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1019, 187, 782, 1707 }
	end
end
do
	local player = players["undrcvrsleyr"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6419, 94, 295, 2623 }
	end
end
do
	local player = players["maxell"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4007, 145, 493, 2135 }
	end
end
do
	local player = players["nosos"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7113, 86, 238, 2830 }
	end
end
do
	local player = players["shandras"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6013, 49, 123, 9768 }
	end
end
do
	local player = players["nótánk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4829, 238, 769, 9465 }
	end
end
do
	local player = players["zâsou"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4714, 247, 815, 9240 }
	end
end
do
	local player = players["blueleyes"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4287, 278, 1006, 8403 }
	end
end
do
	local player = players["zuripatrick"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9824, 12, 23, 17057 }
	end
end
do
	local player = players["vandòr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7536, 125, 309, 12155 }
	end
end
do
	local player = players["zaider"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9304, 48, 88, 15201 }
	end
end
do
	local player = players["sképsis"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4656, 251, 842, 9126 }
	end
end
do
	local player = players["debile"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8240, 101, 221, 12936 }
	end
end
do
	local player = players["yevet"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3021, 158, 574, 2019 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4648, 252, 848, 9111 }
	end
end
do
	local player = players["wowexe"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5156, 68, 190, 8620 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4094, 294, 1070, 8024 }
	end
end
do
	local player = players["dracati"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4460, 85, 247, 7456 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4250, 280, 1021, 8330 }
	end
end
do
	local player = players["inuyaschâ"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4409, 140, 460, 2182 }
	end
end
do
	local player = players["mëlody"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9224, 53, 98, 15013 }
	end
end
do
	local player = players["grendel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5183, 208, 636, 10159 }
	end
end
do
	local player = players["asvid"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9544, 37, 58, 15883 }
	end
end
do
	local player = players["freaký"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5195, 206, 630, 10183 }
	end
end
do
	local player = players["aldaa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4620, 257, 858, 9055 }
	end
end
do
	local player = players["gnomdktank"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4000, 300, 1104, 7840 }
	end
end
do
	local player = players["katitankt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3873, 146, 504, 2114 }
	end
end
do
	local player = players["ciriny"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5025, 71, 209, 8402 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4762, 243, 792, 9333 }
	end
end
do
	local player = players["elkritiko"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6608, 162, 425, 11341 }
	end
end
do
	local player = players["tisiphoni"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8968, 65, 130, 14194 }
	end
end
do
	local player = players["aresor"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6616, 161, 424, 11348 }
	end
end
do
	local player = players["gryzzlêê"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5646, 200, 606, 9749 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7930, 25, 48, 83 }
	end
end
do
	local player = players["owltist"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9551, 34, 55, 14989 }
	end
end
do
	local player = players["telrak"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3474, 300, 1103, 5999 }
	end
end
do
	local player = players["tameimpaler"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7506, 117, 301, 11989 }
	end
end
do
	local player = players["mcdud"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8180, 88, 220, 12913 }
	end
end
do
	local player = players["flaxó"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6293, 163, 447, 10799 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6211, 39, 87, 18 }
	end
end
do
	local player = players["liebstê"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6097, 176, 498, 10527 }
	end
end
do
	local player = players["drood"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7606, 112, 289, 12095 }
	end
end
do
	local player = players["fyláx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5823, 191, 561, 10054 }
	end
end
do
	local player = players["velldora"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5355, 215, 686, 9246 }
	end
end
do
	local player = players["maourie"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5705, 197, 592, 9850 }
	end
end
do
	local player = players["aponia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6091, 177, 501, 10516 }
	end
end
do
	local player = players["balisto"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4184, 287, 973, 7224 }
	end
end
do
	local player = players["druidibus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8562, 72, 174, 13610 }
	end
end
do
	local player = players["stellina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5069, 233, 770, 8752 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 800, 93, 211, 0 }
	end
end
do
	local player = players["tathar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4778, 257, 858, 8249 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9912, 3, 3, 636 }
	end
end
do
	local player = players["jeleena"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9210, 44, 96, 14503 }
	end
end
do
	local player = players["schierâ"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5778, 193, 570, 9977 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3000, 71, 162, 1 }
	end
end
do
	local player = players["kalmanar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6409, 160, 433, 10945 }
	end
end
do
	local player = players["duréen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6426, 158, 431, 10949 }
	end
end
do
	local player = players["matzukey"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8163, 90, 222, 12908 }
	end
end
do
	local player = players["lucyxcat"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5867, 185, 547, 10131 }
	end
end
do
	local player = players["tiffylaila"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3943, 294, 1023, 6808 }
	end
end
do
	local player = players["feralicioùs"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5862, 187, 550, 10122 }
	end
end
do
	local player = players["linolia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5312, 220, 696, 9172 }
	end
end
do
	local player = players["cerabrash"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5227, 225, 718, 9026 }
	end
end
do
	local player = players["dudubuck"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7614, 111, 288, 12119 }
	end
end
do
	local player = players["aggrobatin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5183, 227, 733, 8949 }
	end
end
do
	local player = players["paschua"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5856, 189, 553, 10110 }
	end
end
do
	local player = players["mightymizer"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4751, 259, 865, 8203 }
	end
end
do
	local player = players["klekonis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4998, 241, 795, 8629 }
	end
end
do
	local player = players["diliy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3591, 298, 1089, 6201 }
	end
end
do
	local player = players["effchen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4489, 273, 922, 7750 }
	end
end
do
	local player = players["cardoras"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4454, 104, 288, 7755 }
	end
end
do
	local player = players["traumwind"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4094, 106, 295, 7128 }
	end
end
do
	local player = players["suji"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7686, 40, 85, 11644 }
	end
end
do
	local player = players["neferpito"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2381, 319, 1191, 4112 }
	end
end
do
	local player = players["mediocremezi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1718, 84, 189, 0 }
	end
end
do
	local player = players["zeratuel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4039, 203, 955, 8090 }
	end
end
do
	local player = players["gesichtpalme"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5201, 146, 656, 9590 }
	end
end
do
	local player = players["lieferambo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3979, 209, 972, 7969 }
	end
end
do
	local player = players["vallen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4115, 198, 928, 8241 }
	end
end
do
	local player = players["ajina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5729, 139, 584, 9987 }
	end
end
do
	local player = players["phalanora"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5407, 142, 628, 9732 }
	end
end
do
	local player = players["hetzenauer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9018, 48, 135, 15426 }
	end
end
do
	local player = players["raera"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3982, 207, 970, 7976 }
	end
end
do
	local player = players["snuggs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4857, 157, 703, 9373 }
	end
end
do
	local player = players["mcshotalot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5861, 132, 566, 10085 }
	end
end
do
	local player = players["loktra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8484, 65, 208, 14458 }
	end
end
do
	local player = players["huntzi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7392, 96, 357, 11684 }
	end
end
do
	local player = players["sunset"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4555, 167, 745, 9122 }
	end
end
do
	local player = players["púppy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2762, 253, 1256, 5531 }
	end
end
do
	local player = players["jagtdichhoch"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3637, 224, 1075, 7283 }
	end
end
do
	local player = players["elgwen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4508, 173, 769, 9028 }
	end
end
do
	local player = players["kunoh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7736, 82, 310, 12210 }
	end
end
do
	local player = players["radêsh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6916, 108, 422, 11082 }
	end
end
do
	local player = players["thendrom"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9377, 36, 86, 16165 }
	end
end
do
	local player = players["neonora"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3237, 242, 1178, 6483 }
	end
end
do
	local player = players["pewkrachbumm"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4753, 30, 55, 8498 }
	end
end
do
	local player = players["qodge"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3309, 418, 1523, 7274 }
	end
end
do
	local player = players["fime"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5427, 246, 844, 11930 }
	end
end
do
	local player = players["miriia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9019, 89, 160, 17270 }
	end
end
do
	local player = players["softhorn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7853, 135, 349, 15307 }
	end
end
do
	local player = players["wosh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5181, 276, 983, 11389 }
	end
end
do
	local player = players["serwantes"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3988, 389, 1407, 8765 }
	end
end
do
	local player = players["jondoo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9414, 60, 96, 18149 }
	end
end
do
	local player = players["nosverato"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8267, 114, 282, 16114 }
	end
end
do
	local player = players["arcuria"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4920, 306, 1112, 10814 }
	end
end
do
	local player = players["fixidoller"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5681, 226, 734, 12487 }
	end
end
do
	local player = players["zockenoletwo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5759, 217, 693, 12658 }
	end
end
do
	local player = players["malacay"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4908, 308, 1116, 10789 }
	end
end
do
	local player = players["vakes"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4863, 313, 1137, 10690 }
	end
end
do
	local player = players["ironjoe"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7335, 155, 433, 14460 }
	end
end
do
	local player = players["hëra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4576, 337, 1234, 10059 }
	end
end
do
	local player = players["pubsi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6663, 179, 542, 13527 }
	end
end
do
	local player = players["thaloria"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6397, 191, 585, 13212 }
	end
end
do
	local player = players["strômberg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8723, 103, 208, 16856 }
	end
end
do
	local player = players["kuraiha"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5519, 240, 813, 12132 }
	end
end
do
	local player = players["maggandi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5458, 246, 838, 11997 }
	end
end
do
	local player = players["snoozle"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5297, 263, 916, 11642 }
	end
end
do
	local player = players["unalakleet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6046, 207, 642, 12911 }
	end
end
do
	local player = players["magebens"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4962, 302, 1090, 10906 }
	end
end
do
	local player = players["maleficus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6373, 193, 589, 13195 }
	end
end
do
	local player = players["eislanze"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8007, 123, 324, 15672 }
	end
end
do
	local player = players["paydon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3243, 421, 1535, 7127 }
	end
end
do
	local player = players["adøk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5207, 272, 968, 11445 }
	end
end
do
	local player = players["schieberjung"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5006, 296, 1065, 11005 }
	end
end
do
	local player = players["bromberry"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4167, 363, 1351, 9159 }
	end
end
do
	local player = players["firemos"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8205, 116, 292, 15977 }
	end
end
do
	local player = players["toeten"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9186, 77, 133, 17755 }
	end
end
do
	local player = players["flüchtlinglg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5479, 244, 829, 12043 }
	end
end
do
	local player = players["cystor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5004, 298, 1068, 10999 }
	end
end
do
	local player = players["missundercvr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5684, 225, 732, 12494 }
	end
end
do
	local player = players["großmagierr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5366, 254, 879, 11796 }
	end
end
do
	local player = players["schlem"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5337, 258, 901, 11732 }
	end
end
do
	local player = players["sayala"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5630, 233, 755, 12376 }
	end
end
do
	local player = players["kopist"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3627, 406, 1482, 7973 }
	end
end
do
	local player = players["shinjiaa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6601, 180, 552, 13412 }
	end
end
do
	local player = players["allwero"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4797, 317, 1155, 10544 }
	end
end
do
	local player = players["fossel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8452, 110, 252, 16455 }
	end
end
do
	local player = players["ketaminkaren"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4762, 315, 1161, 10467 }
	end
end
do
	local player = players["callmestacy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3353, 186, 552, 177 }
	end
end
do
	local player = players["nasheri"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9228, 39, 65, 336 }
	end
end
do
	local player = players["izakaya"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6731, 105, 272, 237 }
	end
end
do
	local player = players["reservedose"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2943, 190, 586, 170 }
	end
end
do
	local player = players["bluemind"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6502, 112, 291, 230 }
	end
end
do
	local player = players["ôlympîa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 880, 224, 772, 125 }
	end
end
do
	local player = players["lyniil"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 596, 234, 820, 85 }
	end
end
do
	local player = players["olivenöl"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5127, 144, 405, 206 }
	end
end
do
	local player = players["thaluu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6900, 99, 258, 240 }
	end
end
do
	local player = players["adri"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9819, 12, 16, 447 }
	end
end
do
	local player = players["góldstáénder"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5356, 148, 627, 3434 }
	end
end
do
	local player = players["xenedra"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 24, 239, 830, 3 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4147, 173, 790, 2746 }
	end
end
do
	local player = players["pface"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6634, 109, 280, 235 }
	end
end
do
	local player = players["leuchti"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7077, 92, 395, 4634 }
	end
end
do
	local player = players["règi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8468, 60, 128, 291 }
	end
end
do
	local player = players["pladain"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5344, 139, 387, 209 }
	end
end
do
	local player = players["alwi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3076, 189, 575, 172 }
	end
end
do
	local player = players["fetzér"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 765, 230, 800, 108 }
	end
end
do
	local player = players["napfelbier"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4125, 169, 488, 189 }
	end
end
do
	local player = players["bankdigga"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2604, 203, 998, 1248 }
	end
end
do
	local player = players["protlock"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5660, 139, 586, 3597 }
	end
end
do
	local player = players["demonshell"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2666, 199, 609, 165 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9013, 37, 134, 7036 }
	end
end
do
	local player = players["síndarin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8736, 74, 159, 13842 }
	end
end
do
	local player = players["rangdingdøng"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6988, 95, 407, 4546 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3949, 353, 1133, 7119 }
	end
end
do
	local player = players["áchlys"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9176, 50, 104, 14592 }
	end
end
do
	local player = players["treena"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5365, 231, 600, 9671 }
	end
end
do
	local player = players["daandere"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5059, 271, 751, 9120 }
	end
end
do
	local player = players["celenya"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9104, 53, 113, 14473 }
	end
end
do
	local player = players["rattig"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5480, 219, 566, 9793 }
	end
end
do
	local player = players["rohaya"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6936, 150, 384, 10919 }
	end
end
do
	local player = players["levzwerg"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4634, 313, 928, 8353 }
	end
end
do
	local player = players["stacía"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5334, 149, 630, 3429 }
	end
end
do
	local player = players["ncnc"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5728, 206, 535, 9939 }
	end
end
do
	local player = players["delerius"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3081, 380, 1233, 5555 }
	end
end
do
	local player = players["aldoros"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5536, 216, 559, 9810 }
	end
end
do
	local player = players["palaniâ"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5144, 260, 704, 9273 }
	end
end
do
	local player = players["catvivi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9576, 32, 54, 15613 }
	end
end
do
	local player = players["pzychó"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 390, 238, 828, 55 }
	end
end
do
	local player = players["laurantra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6816, 159, 399, 10811 }
	end
end
do
	local player = players["sornêy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2923, 382, 1237, 5269 }
	end
end
do
	local player = players["yuleria"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5315, 237, 618, 9582 }
	end
end
do
	local player = players["donkowalksi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8359, 65, 137, 289 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5920, 135, 551, 3766 }
	end
end
do
	local player = players["palock"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5415, 223, 576, 9762 }
	end
end
do
	local player = players["acrololz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6528, 115, 469, 4172 }
	end
end
do
	local player = players["ardix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7537, 78, 333, 5134 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4178, 341, 1077, 7531 }
	end
end
do
	local player = players["dadreon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8576, 81, 179, 13697 }
	end
end
do
	local player = players["malenya"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7328, 141, 335, 11440 }
	end
end
do
	local player = players["wingsradikal"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3509, 187, 876, 1831 }
	end
end
do
	local player = players["lightsûn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6248, 184, 470, 10294 }
	end
end
do
	local player = players["memeblaster"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3279, 192, 907, 1582 }
	end
end
do
	local player = players["xirendra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4797, 301, 871, 8648 }
	end
end
do
	local player = players["shutaras"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6558, 113, 465, 4200 }
	end
end
do
	local player = players["zwirn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4466, 326, 985, 8051 }
	end
end
do
	local player = players["manasuchtie"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7384, 137, 328, 11523 }
	end
end
do
	local player = players["barosos"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3725, 364, 1168, 6715 }
	end
end
do
	local player = players["aktenzeichen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7604, 76, 324, 5206 }
	end
end
do
	local player = players["eléktron"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8088, 102, 240, 12510 }
	end
end
do
	local player = players["kazorum"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5957, 134, 546, 3785 }
	end
end
do
	local player = players["lírea"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5200, 252, 677, 9373 }
	end
end
do
	local player = players["darathor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4733, 165, 711, 3117 }
	end
end
do
	local player = players["narioa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5409, 224, 579, 9751 }
	end
end
do
	local player = players["ojemíne"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7826, 72, 294, 5495 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3971, 352, 1129, 7159 }
	end
end
do
	local player = players["ghóstface"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3003, 161, 467, 74 }
	end
end
do
	local player = players["norcaine"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7297, 82, 181, 160 }
	end
end
do
	local player = players["ximts"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2703, 165, 487, 70 }
	end
end
do
	local player = players["yarilla"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5616, 113, 293, 112 }
	end
end
do
	local player = players["maylina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5766, 110, 283, 115 }
	end
end
do
	local player = players["dischzy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1126, 189, 592, 16 }
	end
end
do
	local player = players["nhyreia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5465, 119, 303, 109 }
	end
end
do
	local player = players["heilgöttin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4061, 282, 881, 7961 }
	end
end
do
	local player = players["cric"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8974, 7, 17, 559 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6384, 171, 466, 10809 }
	end
end
do
	local player = players["spiderswine"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4104, 275, 861, 8046 }
	end
end
do
	local player = players["thesplitface"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5894, 181, 529, 10357 }
	end
end
do
	local player = players["tidúz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3740, 308, 995, 7332 }
	end
end
do
	local player = players["druffer"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3553, 326, 1069, 6966 }
	end
end
do
	local player = players["gulaschfrau"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4311, 259, 793, 8451 }
	end
end
do
	local player = players["rîva"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5101, 211, 631, 9581 }
	end
end
do
	local player = players["bncd"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5327, 202, 602, 9815 }
	end
end
do
	local player = players["dojio"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4686, 235, 692, 9186 }
	end
end
do
	local player = players["fuqoff"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6579, 165, 441, 10961 }
	end
end
do
	local player = players["venesti"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9269, 51, 95, 14814 }
	end
end
do
	local player = players["bæbyspeck"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9767, 18, 31, 16123 }
	end
end
do
	local player = players["elitaria"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4460, 249, 750, 8744 }
	end
end
do
	local player = players["ratenzahlung"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9619, 29, 50, 15564 }
	end
end
do
	local player = players["sidejack"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4137, 274, 848, 8111 }
	end
end
do
	local player = players["arcysa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3491, 329, 1088, 6844 }
	end
end
do
	local player = players["álîcè"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7939, 120, 266, 12206 }
	end
end
do
	local player = players["shurtugál"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4578, 243, 718, 8974 }
	end
end
do
	local player = players["balfour"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9393, 45, 79, 15024 }
	end
end
do
	local player = players["üben"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4257, 264, 813, 8345 }
	end
end
do
	local player = players["mirajáné"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9751, 20, 33, 16031 }
	end
end
do
	local player = players["havenfire"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6190, 177, 491, 10621 }
	end
end
do
	local player = players["polopriest"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3740, 302, 986, 7333 }
	end
end
do
	local player = players["xelioa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3719, 313, 1008, 7290 }
	end
end
do
	local player = players["jolla"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4144, 272, 846, 8123 }
	end
end
do
	local player = players["praylorswift"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8631, 89, 177, 12991 }
	end
end
do
	local player = players["leckesel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3574, 324, 1064, 7007 }
	end
end
do
	local player = players["dionysus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6231, 99, 252, 130 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 385, 56, 151, 0 }
	end
end
do
	local player = players["wurstbiene"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5062, 213, 636, 9566 }
	end
end
do
	local player = players["visiøn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7613, 132, 308, 11944 }
	end
end
do
	local player = players["nanashy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7237, 86, 185, 159 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5256, 39, 75, 103 }
	end
end
do
	local player = players["càra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5879, 183, 531, 10344 }
	end
end
do
	local player = players["zocha"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2795, 348, 1232, 5478 }
	end
end
do
	local player = players["peremptor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5014, 196, 815, 9264 }
	end
end
do
	local player = players["stolperfallê"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7955, 76, 255, 12711 }
	end
end
do
	local player = players["sqarstealth"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7593, 92, 300, 12071 }
	end
end
do
	local player = players["krötenuschi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8857, 45, 143, 14414 }
	end
end
do
	local player = players["cybôrk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5423, 156, 587, 10019 }
	end
end
do
	local player = players["mcstealthy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4568, 227, 1023, 8441 }
	end
end
do
	local player = players["trixxen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5088, 190, 782, 9401 }
	end
end
do
	local player = players["dmgcombo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5273, 171, 668, 9743 }
	end
end
do
	local player = players["backpfeifee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5033, 193, 807, 9299 }
	end
end
do
	local player = players["rotrip"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7649, 90, 293, 12133 }
	end
end
do
	local player = players["kysum"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4835, 207, 908, 8933 }
	end
end
do
	local player = players["cherrylady"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7295, 101, 337, 11574 }
	end
end
do
	local player = players["creamslimy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7882, 80, 264, 12546 }
	end
end
do
	local player = players["zeð"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8527, 60, 184, 13713 }
	end
end
do
	local player = players["xeragor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5157, 183, 736, 9528 }
	end
end
do
	local player = players["avocadodipp"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3413, 114, 366, 7416 }
	end
end
do
	local player = players["nuseam"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2755, 119, 385, 5985 }
	end
end
do
	local player = players["mctrololol"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4362, 195, 549, 47 }
	end
end
do
	local player = players["mutsumi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5336, 60, 197, 11592 }
	end
end
do
	local player = players["meziege"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3158, 216, 666, 25 }
	end
end
do
	local player = players["haoasakura"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3571, 113, 356, 7758 }
	end
end
do
	local player = players["spiritbuck"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7078, 126, 285, 131 }
	end
end
do
	local player = players["élaria"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1296, 250, 847, 1 }
	end
end
do
	local player = players["stepmomx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2675, 230, 713, 19 }
	end
end
do
	local player = players["kinura"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 844, 262, 891, 0 }
	end
end
do
	local player = players["ampora"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 141, 281, 963, 0 }
	end
end
do
	local player = players["lastsummer"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 951, 258, 882, 0 }
	end
end
do
	local player = players["muhschock"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1214, 253, 855, 1 }
	end
end
do
	local player = players["cordyhaste"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2202, 238, 759, 12 }
	end
end
do
	local player = players["apôllon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7438, 111, 250, 155 }
	end
end
do
	local player = players["ua"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4640, 189, 522, 53 }
	end
end
do
	local player = players["oggie"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7407, 113, 253, 154 }
	end
end
do
	local player = players["tremorhax"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4095, 201, 575, 42 }
	end
end
do
	local player = players["pringli"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5168, 64, 211, 11228 }
	end
end
do
	local player = players["gehehm"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9002, 49, 98, 818 }
	end
end
do
	local player = players["píxxíe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 352, 275, 950, 0 }
	end
end
do
	local player = players["regnella"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9516, 32, 48, 1412 }
	end
end
do
	local player = players["toilettnadir"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6975, 128, 295, 126 }
	end
end
do
	local player = players["daddyistda"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4827, 73, 236, 10488 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2891, 223, 692, 21 }
	end
end
do
	local player = players["napfelshorle"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1728, 243, 805, 6 }
	end
end
do
	local player = players["nuraushilfe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1698, 244, 808, 5 }
	end
end
do
	local player = players["waisentotem"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8354, 75, 161, 375 }
	end
end
do
	local player = players["píccolo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3251, 212, 657, 26 }
	end
end
do
	local player = players["guldanramsay"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5053, 149, 424, 9901 }
	end
end
do
	local player = players["harrydottèr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5030, 151, 428, 9856 }
	end
end
do
	local player = players["dîablo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5375, 139, 383, 10268 }
	end
end
do
	local player = players["locasta"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8184, 75, 151, 13037 }
	end
end
do
	local player = players["gnommitzopf"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8329, 71, 139, 13258 }
	end
end
do
	local player = players["valka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4511, 178, 527, 8838 }
	end
end
do
	local player = players["skillgap"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6259, 119, 310, 10947 }
	end
end
do
	local player = players["inquisitionz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4067, 215, 644, 7968 }
	end
end
do
	local player = players["azalian"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8414, 69, 132, 13543 }
	end
end
do
	local player = players["hexopeck"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7930, 80, 172, 12555 }
	end
end
do
	local player = players["hafiza"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3718, 230, 713, 7285 }
	end
end
do
	local player = players["ningendou"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6586, 109, 283, 11221 }
	end
end
do
	local player = players["xirilla"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4368, 191, 564, 8559 }
	end
end
do
	local player = players["ørbeit"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6864, 106, 260, 11520 }
	end
end
do
	local player = players["oiskipoiski"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3909, 223, 675, 7659 }
	end
end
do
	local player = players["kurochan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4372, 189, 561, 8566 }
	end
end
do
	local player = players["tundacrist"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4590, 337, 1313, 12278 }
	end
end
do
	local player = players["chemo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4396, 346, 1360, 12083 }
	end
end
do
	local player = players["orcaholics"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6808, 235, 775, 14983 }
	end
end
do
	local player = players["stérben"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5406, 300, 1115, 13119 }
	end
end
do
	local player = players["brutalismus"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6623, 31, 103, 3303 }
	end
end
do
	local player = players["tabacco"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7654, 173, 570, 16365 }
	end
end
do
	local player = players["müllholde"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3786, 413, 1843, 10427 }
	end
end
do
	local player = players["damageseb"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9435, 58, 138, 21980 }
	end
end
do
	local player = players["tangalina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6487, 246, 853, 14532 }
	end
end
do
	local player = players["stevewütend"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4212, 369, 1490, 11601 }
	end
end
do
	local player = players["borgnager"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3433, 441, 2104, 9455 }
	end
end
do
	local player = players["induktion"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4561, 341, 1320, 12254 }
	end
end
do
	local player = players["shierack"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4130, 374, 1554, 11376 }
	end
end
do
	local player = players["ðarkstorm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8635, 118, 332, 19166 }
	end
end
do
	local player = players["risenhuman"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5138, 317, 1180, 12836 }
	end
end
do
	local player = players["steinbrutalo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8322, 136, 408, 18114 }
	end
end
do
	local player = players["kibanery"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3380, 443, 2135, 9310 }
	end
end
do
	local player = players["aveiroo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8029, 158, 479, 17244 }
	end
end
do
	local player = players["kilomatik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3084, 465, 2283, 8495 }
	end
end
do
	local player = players["flaxø"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4594, 336, 1312, 12282 }
	end
end
do
	local player = players["hallowean"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5930, 279, 988, 13745 }
	end
end
do
	local player = players["kampfmakrele"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8441, 129, 379, 18574 }
	end
end
do
	local player = players["barashork"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6577, 241, 831, 14643 }
	end
end
do
	local player = players["zefixnamoi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3657, 422, 1949, 10071 }
	end
end
do
	local player = players["mekarius"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8693, 114, 318, 19274 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6159, 39, 117, 3145 }
	end
end
do
	local player = players["bonerschelle"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8532, 126, 357, 18865 }
	end
end
do
	local player = players["smittywerben"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3478, 436, 2075, 9578 }
	end
end
do
	local player = players["karkarottê"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5645, 295, 1057, 13419 }
	end
end
do
	local player = players["sladgø"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7093, 209, 706, 15416 }
	end
end
do
	local player = players["roliroland"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6973, 220, 735, 15215 }
	end
end
do
	local player = players["blinkeykri"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6004, 275, 970, 13872 }
	end
end
do
	local player = players["apollonir"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3535, 430, 2030, 9736 }
	end
end
do
	local player = players["savitir"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8573, 121, 347, 18927 }
	end
end
do
	local player = players["alphäus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6421, 248, 869, 14480 }
	end
end
do
	local player = players["paulchen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7518, 181, 603, 16010 }
	end
end
do
	local player = players["hathór"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9303, 65, 170, 21515 }
	end
end
do
	local player = players["takco"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8404, 132, 388, 18463 }
	end
end
do
	local player = players["dídler"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5889, 282, 998, 13683 }
	end
end
do
	local player = players["talaxin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6548, 242, 838, 14607 }
	end
end
do
	local player = players["dræbeiris"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3341, 449, 2161, 9201 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5629, 49, 133, 2750 }
	end
end
do
	local player = players["ârès"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9080, 85, 224, 20740 }
	end
end
do
	local player = players["wakeup"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6882, 228, 757, 15081 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
