-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "voa"
local chunkStartIndex = 6912
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["dacarma"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5800, 192, 274, 2723 }
	end
end
do
	local player = players["donkoowalski"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7586, 106, 158, 3517 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6524, 136, 172, 9250 }
	end
end
do
	local player = players["innodeekaay"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7908, 92, 144, 3734 }
	end
end
do
	local player = players["sïrï"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 844, 416, 614, 1683 }
	end
end
do
	local player = players["jornala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7338, 120, 174, 3290 }
	end
end
do
	local player = players["âffemîtwaffe"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4569, 244, 354, 2478 }
	end
end
do
	local player = players["taeca"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4100, 419, 660, 7671 }
	end
end
do
	local player = players["pishorc"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3231, 306, 441, 2270 }
	end
end
do
	local player = players["seuthe"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9788, 10, 16, 14288 }
	end
end
do
	local player = players["dayria"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9379, 28, 47, 10986 }
	end
end
do
	local player = players["jîya"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6677, 149, 217, 2942 }
	end
end
do
	local player = players["ravean"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1292, 386, 567, 1903 }
	end
end
do
	local player = players["galadrâ"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7977, 89, 140, 3755 }
	end
end
do
	local player = players["darkwingdead"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7700, 148, 225, 11651 }
	end
end
do
	local player = players["necuro"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6385, 164, 236, 2841 }
	end
end
do
	local player = players["runénfaust"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7031, 134, 194, 3131 }
	end
end
do
	local player = players["caryssia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3277, 303, 438, 2279 }
	end
end
do
	local player = players["nosos"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7077, 131, 191, 3156 }
	end
end
do
	local player = players["kapodk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2538, 339, 486, 2150 }
	end
end
do
	local player = players["grollbard"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5108, 224, 319, 2558 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4230, 397, 626, 7915 }
	end
end
do
	local player = players["deathnerd"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9849, 6, 9, 15363 }
	end
end
do
	local player = players["areila"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7154, 109, 141, 9814 }
	end
end
do
	local player = players["käptniglu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7988, 82, 100, 10634 }
	end
end
do
	local player = players["hekàté"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8191, 76, 90, 10764 }
	end
end
do
	local player = players["rafíki"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8391, 71, 116, 5100 }
	end
end
do
	local player = players["furorius"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8638, 57, 68, 11297 }
	end
end
do
	local player = players["ritterlix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7541, 98, 122, 10155 }
	end
end
do
	local player = players["callmewifey"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4146, 207, 289, 7726 }
	end
end
do
	local player = players["zuripatrick"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4815, 323, 506, 8985 }
	end
end
do
	local player = players["iïl"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8511, 102, 146, 12751 }
	end
end
do
	local player = players["thedêâth"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8398, 109, 157, 12561 }
	end
end
do
	local player = players["vandòr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8111, 127, 185, 12187 }
	end
end
do
	local player = players["zaider"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7402, 168, 254, 11234 }
	end
end
do
	local player = players["debile"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8747, 85, 123, 13069 }
	end
end
do
	local player = players["wowexe"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8720, 53, 64, 11373 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8409, 108, 156, 12575 }
	end
end
do
	local player = players["twsabine"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6099, 243, 381, 10109 }
	end
end
do
	local player = players["teriané"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7587, 157, 236, 11469 }
	end
end
do
	local player = players["napfelcore"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7916, 135, 204, 11885 }
	end
end
do
	local player = players["grendel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8645, 91, 133, 12866 }
	end
end
do
	local player = players["finuh"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9322, 46, 67, 14238 }
	end
end
do
	local player = players["asvid"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6109, 242, 380, 10127 }
	end
end
do
	local player = players["dêâthnix"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8686, 88, 129, 12904 }
	end
end
do
	local player = players["rûm"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5412, 285, 450, 9409 }
	end
end
do
	local player = players["nexurix"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1938, 360, 525, 2050 }
	end
end
do
	local player = players["fôrtuná"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8532, 101, 144, 12759 }
	end
end
do
	local player = players["marsupilamii"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8871, 76, 111, 13181 }
	end
end
do
	local player = players["newwompada"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9774, 15, 24, 15747 }
	end
end
do
	local player = players["ratatoeskr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5428, 284, 448, 9414 }
	end
end
do
	local player = players["antîengel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6684, 211, 324, 10555 }
	end
end
do
	local player = players["katitankt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7747, 99, 151, 3594 }
	end
end
do
	local player = players["ástra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3752, 464, 728, 7019 }
	end
end
do
	local player = players["ciriny"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4911, 316, 497, 9045 }
	end
end
do
	local player = players["botlevel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8819, 81, 116, 13113 }
	end
end
do
	local player = players["elkritiko"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7772, 145, 218, 11713 }
	end
end
do
	local player = players["gògeta"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7813, 141, 214, 11760 }
	end
end
do
	local player = players["darkestdrake"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4796, 324, 508, 8973 }
	end
end
do
	local player = players["zisis"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5986, 250, 392, 10015 }
	end
end
do
	local player = players["weedwinzer"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9952, 6, 6, 15387 }
	end
end
do
	local player = players["eulengerät"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9277, 54, 76, 12971 }
	end
end
do
	local player = players["tameimpaler"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1481, 688, 1027, 2393 }
	end
end
do
	local player = players["drood"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8891, 82, 116, 12159 }
	end
end
do
	local player = players["rhyounos"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9383, 47, 65, 13153 }
	end
end
do
	local player = players["talerhuhn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4884, 372, 547, 7893 }
	end
end
do
	local player = players["stellina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4950, 365, 537, 8000 }
	end
end
do
	local player = players["felltomate"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9499, 36, 53, 13437 }
	end
end
do
	local player = players["syoxs"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8206, 134, 187, 11101 }
	end
end
do
	local player = players["jeleena"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9769, 21, 25, 14168 }
	end
end
do
	local player = players["dêmontieren"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9094, 66, 95, 12557 }
	end
end
do
	local player = players["lucyxcat"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8349, 90, 161, 10759 }
	end
end
do
	local player = players["antibengel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9605, 30, 42, 13697 }
	end
end
do
	local player = players["andiheiler"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6037, 278, 412, 8924 }
	end
end
do
	local player = players["therealpara"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6297, 260, 385, 9177 }
	end
end
do
	local player = players["tiffylaila"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8881, 83, 117, 12093 }
	end
end
do
	local player = players["doomkuh"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7734, 169, 236, 10565 }
	end
end
do
	local player = players["syhu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5044, 354, 521, 8153 }
	end
end
do
	local player = players["lariniel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8997, 74, 105, 12318 }
	end
end
do
	local player = players["cerabrash"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4848, 377, 557, 7835 }
	end
end
do
	local player = players["diliy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9421, 44, 61, 13189 }
	end
end
do
	local player = players["antidruid"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9055, 70, 99, 12526 }
	end
end
do
	local player = players["wykiki"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4952, 364, 536, 8003 }
	end
end
do
	local player = players["kuhliefumden"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8052, 106, 188, 10289 }
	end
end
do
	local player = players["noctius"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7291, 147, 272, 8919 }
	end
end
do
	local player = players["fauchmiau"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8177, 137, 190, 11065 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5603, 238, 434, 6638 }
	end
end
do
	local player = players["malv"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8534, 80, 148, 10952 }
	end
end
do
	local player = players["gwyhn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1720, 498, 838, 3139 }
	end
end
do
	local player = players["aubärgine"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7792, 120, 215, 9753 }
	end
end
do
	local player = players["kâtzengôld"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3154, 370, 627, 4745 }
	end
end
do
	local player = players["mìetzekotze"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2252, 434, 726, 4110 }
	end
end
do
	local player = players["beartrukle"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3636, 344, 591, 5031 }
	end
end
do
	local player = players["kampfkalmar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3803, 335, 577, 5130 }
	end
end
do
	local player = players["wildshape"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3117, 372, 630, 4705 }
	end
end
do
	local player = players["bâûm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7996, 109, 197, 10155 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5300, 87, 95, 4 }
	end
end
do
	local player = players["sniiff"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4527, 296, 524, 5521 }
	end
end
do
	local player = players["kleô"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4150, 107, 118, 3 }
	end
end
do
	local player = players["bruderborke"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6000, 73, 81, 6 }
	end
end
do
	local player = players["hightôwer"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7200, 52, 57, 7 }
	end
end
do
	local player = players["grumgrr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3300, 121, 135, 3 }
	end
end
do
	local player = players["batscho"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4500, 423, 628, 7273 }
	end
end
do
	local player = players["zelino"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6750, 60, 66, 6 }
	end
end
do
	local player = players["mínjung"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6818, 226, 331, 9661 }
	end
end
do
	local player = players["fujiyama"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4515, 422, 627, 7297 }
	end
end
do
	local player = players["exuhunt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7194, 189, 311, 9785 }
	end
end
do
	local player = players["snuggs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7007, 212, 344, 9574 }
	end
end
do
	local player = players["talahont"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9348, 47, 98, 13848 }
	end
end
do
	local player = players["oriôn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8028, 140, 246, 10855 }
	end
end
do
	local player = players["sternentreu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4809, 367, 578, 7660 }
	end
end
do
	local player = players["púppy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7816, 155, 268, 10499 }
	end
end
do
	local player = players["realeyes"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8993, 72, 137, 12872 }
	end
end
do
	local player = players["pêps"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9447, 40, 81, 14316 }
	end
end
do
	local player = players["casteas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9816, 14, 33, 16021 }
	end
end
do
	local player = players["jellybix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8596, 100, 186, 11937 }
	end
end
do
	local player = players["barnee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9362, 46, 96, 13910 }
	end
end
do
	local player = players["thendrom"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9730, 20, 45, 15546 }
	end
end
do
	local player = players["paxxa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7887, 150, 262, 10596 }
	end
end
do
	local player = players["acile"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9248, 54, 107, 13650 }
	end
end
do
	local player = players["veilchenhut"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8695, 93, 174, 12258 }
	end
end
do
	local player = players["hãwkz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8750, 11, 16, 11742 }
	end
end
do
	local player = players["richiefuenf"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9121, 63, 124, 13228 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9250, 7, 12, 13135 }
	end
end
do
	local player = players["ocrana"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3295, 63, 84, 5964 }
	end
end
do
	local player = players["fluchtreflex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9453, 28, 34, 12068 }
	end
end
do
	local player = players["pottihc"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9071, 45, 57, 10741 }
	end
end
do
	local player = players["chinchillaa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8789, 60, 74, 10413 }
	end
end
do
	local player = players["kloschüssel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2321, 374, 538, 4397 }
	end
end
do
	local player = players["fytb"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7326, 198, 286, 11781 }
	end
end
do
	local player = players["shâllâch"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6285, 173, 225, 8025 }
	end
end
do
	local player = players["neesama"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6534, 160, 210, 8198 }
	end
end
do
	local player = players["alwinix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9315, 59, 74, 15390 }
	end
end
do
	local player = players["maiblock"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8696, 103, 140, 13909 }
	end
end
do
	local player = players["shinjiaa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3375, 528, 779, 6790 }
	end
end
do
	local player = players["pubsi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9690, 29, 34, 16483 }
	end
end
do
	local player = players["thaloria"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3229, 549, 808, 6495 }
	end
end
do
	local player = players["paydon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9906, 11, 11, 17535 }
	end
end
do
	local player = players["âmazing"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8846, 92, 124, 14228 }
	end
end
do
	local player = players["pyrî"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4794, 383, 556, 8737 }
	end
end
do
	local player = players["zuriwurst"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5497, 327, 481, 9508 }
	end
end
do
	local player = players["flüchtlinglg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 10000, 1, 1, 20118 }
	end
end
do
	local player = players["firemos"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8462, 121, 165, 13524 }
	end
end
do
	local player = players["andürüm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5450, 330, 486, 9420 }
	end
end
do
	local player = players["allwero"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8011, 152, 213, 12813 }
	end
end
do
	local player = players["meinemutti"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9221, 5, 7, 8236 }
	end
end
do
	local player = players["nasheri"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4664, 305, 390, 147 }
	end
end
do
	local player = players["lyniil"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2702, 408, 533, 102 }
	end
end
do
	local player = players["taylinchen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3608, 365, 467, 125 }
	end
end
do
	local player = players["mcbook"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5929, 168, 231, 3777 }
	end
end
do
	local player = players["valumia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8189, 114, 133, 253 }
	end
end
do
	local player = players["blubberbêrnd"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6008, 229, 292, 186 }
	end
end
do
	local player = players["peterenisx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8985, 64, 75, 299 }
	end
end
do
	local player = players["glänzt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4554, 313, 398, 145 }
	end
end
do
	local player = players["vyathas"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7709, 139, 168, 238 }
	end
end
do
	local player = players["trunkse"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3224, 383, 495, 119 }
	end
end
do
	local player = players["flauschpala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7874, 129, 156, 245 }
	end
end
do
	local player = players["napfelbier"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7339, 157, 195, 225 }
	end
end
do
	local player = players["pklx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8313, 106, 124, 257 }
	end
end
do
	local player = players["fetzér"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3882, 350, 447, 130 }
	end
end
do
	local player = players["percuri"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6968, 177, 222, 212 }
	end
end
do
	local player = players["einlocke"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8285, 108, 126, 256 }
	end
end
do
	local player = players["atropín"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8258, 110, 128, 254 }
	end
end
do
	local player = players["skoeldpadda"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7522, 102, 141, 4231 }
	end
end
do
	local player = players["divinebuck"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4531, 219, 310, 3422 }
	end
end
do
	local player = players["elpete"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8776, 49, 71, 5003 }
	end
end
do
	local player = players["fyläxi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4142, 236, 332, 3348 }
	end
end
do
	local player = players["commodor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8726, 51, 73, 4986 }
	end
end
do
	local player = players["kromnir"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7646, 97, 134, 4290 }
	end
end
do
	local player = players["vermythór"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4035, 240, 338, 3326 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8664, 114, 182, 11954 }
	end
end
do
	local player = players["cecrop"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8765, 78, 91, 282 }
	end
end
do
	local player = players["síndarin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5608, 376, 582, 8476 }
	end
end
do
	local player = players["áchlys"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8851, 99, 153, 12387 }
	end
end
do
	local player = players["treena"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7735, 93, 129, 4319 }
	end
end
do
	local player = players["daandere"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8345, 141, 223, 11386 }
	end
end
do
	local player = players["gladio"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9872, 15, 18, 14698 }
	end
end
do
	local player = players["greedyeyes"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7082, 252, 387, 9838 }
	end
end
do
	local player = players["rohaya"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9879, 14, 17, 14782 }
	end
end
do
	local player = players["stacía"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6266, 320, 495, 9113 }
	end
end
do
	local player = players["levzwerg"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3868, 351, 448, 129 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7173, 242, 375, 9914 }
	end
end
do
	local player = players["gabaton"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7805, 134, 161, 240 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6379, 314, 480, 9198 }
	end
end
do
	local player = players["ncnc"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9584, 44, 56, 13738 }
	end
end
do
	local player = players["rylani"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7876, 89, 121, 4403 }
	end
end
do
	local player = players["jordbjørn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8464, 98, 113, 262 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8783, 104, 164, 12255 }
	end
end
do
	local player = players["loladìn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6228, 217, 276, 192 }
	end
end
do
	local player = players["donkowalksi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9388, 25, 38, 5995 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9191, 78, 108, 13052 }
	end
end
do
	local player = players["palock"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7551, 211, 325, 10355 }
	end
end
do
	local player = players["engelien"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2497, 414, 548, 96 }
	end
end
do
	local player = players["paulyoung"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6561, 297, 456, 9384 }
	end
end
do
	local player = players["palâeins"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9337, 27, 40, 5889 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9569, 46, 58, 13727 }
	end
end
do
	local player = players["malenya"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9516, 51, 65, 13560 }
	end
end
do
	local player = players["roná"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4602, 216, 306, 3435 }
	end
end
do
	local player = players["manasuchtie"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1605, 453, 613, 72 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9433, 61, 76, 13393 }
	end
end
do
	local player = players["barosos"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9841, 19, 22, 14429 }
	end
end
do
	local player = players["flummerdin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4422, 537, 812, 7165 }
	end
end
do
	local player = players["aktenzeichen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9752, 12, 15, 7581 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9410, 63, 79, 13351 }
	end
end
do
	local player = players["keegan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8416, 128, 201, 11650 }
	end
end
do
	local player = players["anêla"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2315, 354, 515, 2263 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2702, 734, 1125, 4379 }
	end
end
do
	local player = players["thens"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9826, 21, 24, 14394 }
	end
end
do
	local player = players["aeriwin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2472, 743, 1142, 4005 }
	end
end
do
	local player = players["ojemíne"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8239, 150, 236, 11240 }
	end
end
do
	local player = players["zeliá"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7583, 76, 88, 193 }
	end
end
do
	local player = players["vylînda"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9389, 18, 23, 283 }
	end
end
do
	local player = players["hooniig"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8222, 58, 65, 208 }
	end
end
do
	local player = players["butwhaylor"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2855, 663, 1025, 4372 }
	end
end
do
	local player = players["sazzara"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 594, 80, 96, 2 }
	end
end
do
	local player = players["yuri"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8336, 125, 196, 10851 }
	end
end
do
	local player = players["dojio"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9800, 19, 24, 13890 }
	end
end
do
	local player = players["tøø"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6872, 234, 361, 9015 }
	end
end
do
	local player = players["sharlora"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9531, 39, 55, 13101 }
	end
end
do
	local player = players["blliink"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9522, 40, 56, 13094 }
	end
end
do
	local player = players["crâzy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9123, 69, 102, 12351 }
	end
end
do
	local player = players["redrodnsoahc"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9826, 16, 21, 13935 }
	end
end
do
	local player = players["dionysus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7361, 82, 96, 190 }
	end
end
do
	local player = players["wurstbiene"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9609, 34, 46, 13197 }
	end
end
do
	local player = players["fluchprophet"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9131, 68, 101, 12377 }
	end
end
do
	local player = players["càra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8550, 109, 173, 11144 }
	end
end
do
	local player = players["zocha"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8819, 89, 142, 11542 }
	end
end
do
	local player = players["brexy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8455, 18, 30, 11750 }
	end
end
do
	local player = players["pixiepanic"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7824, 25, 38, 10999 }
	end
end
do
	local player = players["strb"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9455, 7, 13, 12798 }
	end
end
do
	local player = players["fallofefrafa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4226, 393, 636, 7667 }
	end
end
do
	local player = players["pushy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7487, 148, 274, 11698 }
	end
end
do
	local player = players["jupptina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7043, 174, 312, 11310 }
	end
end
do
	local player = players["corvata"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4969, 315, 515, 9017 }
	end
end
do
	local player = players["trixxen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3026, 517, 821, 5491 }
	end
end
do
	local player = players["mcstealthy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9138, 58, 83, 14399 }
	end
end
do
	local player = players["rogguide"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5235, 281, 468, 9498 }
	end
end
do
	local player = players["rotrip"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8530, 87, 141, 13499 }
	end
end
do
	local player = players["thebeste"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9842, 13, 16, 16276 }
	end
end
do
	local player = players["ellywoodxx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5966, 237, 400, 10394 }
	end
end
do
	local player = players["joneesbo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6564, 202, 352, 10886 }
	end
end
do
	local player = players["shykra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6085, 230, 392, 10454 }
	end
end
do
	local player = players["kysum"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9853, 12, 15, 16289 }
	end
end
do
	local player = players["sôùéî"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8273, 20, 33, 11241 }
	end
end
do
	local player = players["zocanna"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7471, 30, 44, 10439 }
	end
end
do
	local player = players["fakes"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9548, 33, 44, 15396 }
	end
end
do
	local player = players["shabob"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8791, 73, 116, 13887 }
	end
end
do
	local player = players["jhestil"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5402, 270, 450, 9776 }
	end
end
do
	local player = players["nomercyx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9958, 4, 5, 17272 }
	end
end
do
	local player = players["taschendeep"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8547, 86, 140, 13511 }
	end
end
do
	local player = players["etit"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9306, 49, 67, 14742 }
	end
end
do
	local player = players["stepsisnoya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3314, 499, 784, 6014 }
	end
end
do
	local player = players["crowe"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4868, 79, 123, 7011 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7179, 166, 303, 11408 }
	end
end
do
	local player = players["pepsilight"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3520, 480, 758, 6387 }
	end
end
do
	local player = players["glaukos"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7388, 119, 170, 10014 }
	end
end
do
	local player = players["jellybelly"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8702, 63, 85, 12169 }
	end
end
do
	local player = players["hestìa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3088, 333, 473, 6287 }
	end
end
do
	local player = players["mctrololol"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9480, 24, 36, 14374 }
	end
end
do
	local player = players["arrowgen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9119, 42, 58, 13352 }
	end
end
do
	local player = players["hansg"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7295, 124, 176, 9909 }
	end
end
do
	local player = players["electrofist"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8794, 57, 79, 12491 }
	end
end
do
	local player = players["egorana"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7249, 127, 179, 9863 }
	end
end
do
	local player = players["murdøck"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6105, 186, 253, 8768 }
	end
end
do
	local player = players["nullnullbell"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3271, 313, 445, 6659 }
	end
end
do
	local player = players["martinitot"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7187, 131, 183, 9735 }
	end
end
do
	local player = players["kirlon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9274, 34, 48, 13779 }
	end
end
do
	local player = players["oldfuq"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8300, 77, 111, 11512 }
	end
end
do
	local player = players["réxus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2332, 395, 566, 4748 }
	end
end
do
	local player = players["ashkaran"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9382, 29, 41, 14284 }
	end
end
do
	local player = players["shorrag"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7682, 92, 119, 320 }
	end
end
do
	local player = players["jackycoola"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2699, 257, 423, 5241 }
	end
end
do
	local player = players["ziehmalkaär"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3999, 195, 300, 7767 }
	end
end
do
	local player = players["fazum"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4074, 189, 292, 7912 }
	end
end
do
	local player = players["thríus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7973, 60, 106, 11142 }
	end
end
do
	local player = players["spoonhancer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6632, 99, 163, 10174 }
	end
end
do
	local player = players["versûs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5530, 134, 212, 9349 }
	end
end
do
	local player = players["gaußgewehr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7526, 73, 120, 10874 }
	end
end
do
	local player = players["riptíde"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8591, 42, 70, 12058 }
	end
end
do
	local player = players["quantenhauz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8076, 57, 100, 11331 }
	end
end
do
	local player = players["àntraax"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2742, 256, 420, 5326 }
	end
end
do
	local player = players["nèmrusham"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6955, 123, 156, 105 }
	end
end
do
	local player = players["icezerô"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5572, 132, 210, 9376 }
	end
end
do
	local player = players["venelfur"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7289, 109, 139, 188 }
	end
end
do
	local player = players["muhschock"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4396, 219, 297, 15 }
	end
end
do
	local player = players["stepmomx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3033, 272, 362, 8 }
	end
end
do
	local player = players["evilocity"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3321, 306, 434, 6762 }
	end
end
do
	local player = players["teratøx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9823, 8, 10, 2505 }
	end
end
do
	local player = players["pringli"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9351, 30, 43, 14098 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4370, 220, 298, 15 }
	end
end
do
	local player = players["napfelshorle"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3136, 268, 357, 9 }
	end
end
do
	local player = players["nuraushilfe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3625, 249, 332, 11 }
	end
end
do
	local player = players["shelley"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7919, 93, 137, 10661 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8291, 70, 88, 951 }
	end
end
do
	local player = players["blâckrosé"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5733, 167, 220, 38 }
	end
end
do
	local player = players["valadilène"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3262, 249, 378, 5591 }
	end
end
do
	local player = players["soulshaker"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7810, 78, 116, 10430 }
	end
end
do
	local player = players["neuerchar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9029, 39, 52, 13024 }
	end
end
do
	local player = players["fluchzeug"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7981, 73, 107, 10649 }
	end
end
do
	local player = players["safedigga"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4476, 193, 291, 6941 }
	end
end
do
	local player = players["whitewitch"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2783, 288, 437, 4770 }
	end
end
do
	local player = players["lxej"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7086, 101, 154, 9534 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6179, 180, 275, 8815 }
	end
end
do
	local player = players["hamunæpthra"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5219, 170, 252, 7586 }
	end
end
do
	local player = players["vookshex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5848, 153, 219, 8297 }
	end
end
do
	local player = players["thalric"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4914, 178, 268, 7234 }
	end
end
do
	local player = players["realah"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8686, 47, 70, 12189 }
	end
end
do
	local player = players["lókî"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7943, 74, 109, 10627 }
	end
end
do
	local player = players["chèrryplague"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3108, 262, 399, 5327 }
	end
end
do
	local player = players["lefvers"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7930, 96, 163, 10370 }
	end
end
do
	local player = players["ziller"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9499, 24, 42, 13753 }
	end
end
do
	local player = players["tragthol"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9303, 33, 54, 13381 }
	end
end
do
	local player = players["gestella"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6597, 159, 245, 9215 }
	end
end
do
	local player = players["stiirb"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8889, 52, 99, 11839 }
	end
end
do
	local player = players["hexopeck"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3930, 337, 503, 6430 }
	end
end
do
	local player = players["zvuk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8743, 45, 67, 12336 }
	end
end
do
	local player = players["marocai"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8562, 67, 122, 11184 }
	end
end
do
	local player = players["bixà"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6416, 169, 258, 9004 }
	end
end
do
	local player = players["ørbeit"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7619, 83, 126, 10167 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8214, 83, 146, 10656 }
	end
end
do
	local player = players["oiskipoiski"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7505, 88, 132, 10083 }
	end
end
do
	local player = players["neurose"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5376, 44, 76, 6918 }
	end
end
do
	local player = players["favoritycent"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5591, 42, 73, 7127 }
	end
end
do
	local player = players["yeetkolben"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9608, 3, 5, 11265 }
	end
end
do
	local player = players["sríon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7538, 15, 17, 9336 }
	end
end
do
	local player = players["romace"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5116, 26, 33, 7326 }
	end
end
do
	local player = players["xalyna"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9251, 95, 120, 15608 }
	end
end
do
	local player = players["flinn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8257, 178, 278, 12983 }
	end
end
do
	local player = players["thoraiss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6526, 357, 553, 10292 }
	end
end
do
	local player = players["crownseeker"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9742, 38, 42, 17316 }
	end
end
do
	local player = players["chemo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9893, 18, 18, 18020 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9417, 13, 20, 4529 }
	end
end
do
	local player = players["orcaholics"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5198, 500, 764, 9070 }
	end
end
do
	local player = players["brutalismus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8464, 158, 245, 13512 }
	end
end
do
	local player = players["müllholde"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9484, 68, 83, 16266 }
	end
end
do
	local player = players["nuadosc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3144, 766, 1225, 6507 }
	end
end
do
	local player = players["bongmeister"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8760, 136, 198, 14337 }
	end
end
do
	local player = players["bigsmorc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9660, 49, 55, 16730 }
	end
end
do
	local player = players["ebâý"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6130, 399, 616, 9908 }
	end
end
do
	local player = players["stevewütend"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7283, 57, 76, 3181 }
	end
end
do
	local player = players["klimacleaver"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9390, 82, 98, 15962 }
	end
end
do
	local player = players["adp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5702, 442, 684, 9514 }
	end
end
do
	local player = players["prein"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8874, 129, 180, 14650 }
	end
end
do
	local player = players["shierack"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2428, 878, 1407, 5026 }
	end
end
do
	local player = players["druffman"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9673, 47, 53, 16752 }
	end
end
do
	local player = players["kibanery"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9264, 93, 118, 15650 }
	end
end
do
	local player = players["kilomatik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7168, 291, 451, 11059 }
	end
end
do
	local player = players["glortrololol"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8156, 188, 294, 12654 }
	end
end
do
	local player = players["kêndî"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6709, 340, 524, 10464 }
	end
end
do
	local player = players["blyadstormjr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9767, 34, 38, 17403 }
	end
end
do
	local player = players["sladgø"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2165, 900, 1443, 4481 }
	end
end
do
	local player = players["vashura"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3522, 695, 1097, 7290 }
	end
end
do
	local player = players["gylda"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9119, 107, 141, 15294 }
	end
end
do
	local player = players["weaklee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5727, 438, 680, 9533 }
	end
end
do
	local player = players["ayiibogan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1588, 902, 1456, 3286 }
	end
end
do
	local player = players["anamanisator"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3276, 739, 1183, 6781 }
	end
end
do
	local player = players["hathór"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3369, 718, 1146, 6972 }
	end
end
do
	local player = players["talaxin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6916, 320, 491, 10697 }
	end
end
do
	local player = players["inkompetent"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9062, 111, 150, 15115 }
	end
end
do
	local player = players["gualterio"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1859, 925, 1494, 3847 }
	end
end
do
	local player = players["takco"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7231, 286, 441, 11141 }
	end
end
do
	local player = players["sehrwütend"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6350, 376, 581, 10123 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
