-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "voa"
local chunkStartIndex = 5132
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["kîtetsû"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6274, 167, 235, 2822 }
	end
end
do
	local player = players["vulky"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4459, 243, 349, 2460 }
	end
end
do
	local player = players["morgif"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4889, 226, 322, 2538 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9331, 44, 63, 14237 }
	end
end
do
	local player = players["tankschrank"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4650, 234, 337, 2509 }
	end
end
do
	local player = players["pøky"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9318, 30, 51, 10229 }
	end
end
do
	local player = players["casualclass"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6035, 178, 250, 2767 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9687, 20, 30, 15307 }
	end
end
do
	local player = players["hermius"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9271, 32, 53, 10061 }
	end
end
do
	local player = players["futurefry"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1003, 388, 566, 1793 }
	end
end
do
	local player = players["kesaja"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7150, 127, 180, 3206 }
	end
end
do
	local player = players["temaor"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1146, 382, 557, 1853 }
	end
end
do
	local player = players["shylista"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4841, 227, 325, 2534 }
	end
end
do
	local player = players["hendrikx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 859, 402, 586, 1714 }
	end
end
do
	local player = players["elyza"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9223, 31, 38, 12329 }
	end
end
do
	local player = players["silch"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9517, 19, 24, 13438 }
	end
end
do
	local player = players["ràwpunzel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9118, 34, 43, 12129 }
	end
end
do
	local player = players["miniyarak"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7080, 109, 140, 9800 }
	end
end
do
	local player = players["chèrrycoke"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2876, 258, 385, 5645 }
	end
end
do
	local player = players["starb"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4220, 254, 364, 2427 }
	end
end
do
	local player = players["debl"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6849, 119, 151, 9504 }
	end
end
do
	local player = players["seuchenherr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3032, 252, 371, 5951 }
	end
end
do
	local player = players["darkpuzzy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7143, 106, 137, 9818 }
	end
end
do
	local player = players["kíet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6534, 132, 166, 9284 }
	end
end
do
	local player = players["gortuk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8718, 51, 62, 11404 }
	end
end
do
	local player = players["naltanos"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8047, 126, 182, 12063 }
	end
end
do
	local player = players["deepfried"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9989, 2, 2, 18329 }
	end
end
do
	local player = players["teysøn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9148, 56, 80, 13845 }
	end
end
do
	local player = players["pwndxxq"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4666, 233, 336, 2512 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7314, 171, 250, 11165 }
	end
end
do
	local player = players["ghiulia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6311, 227, 343, 10313 }
	end
end
do
	local player = players["hirschhelles"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6736, 147, 206, 2974 }
	end
end
do
	local player = players["simplydreck"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9396, 39, 57, 14371 }
	end
end
do
	local player = players["zunny"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8069, 125, 180, 12092 }
	end
end
do
	local player = players["seleena"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4061, 261, 374, 2396 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9644, 24, 34, 15233 }
	end
end
do
	local player = players["harvêy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5146, 292, 451, 9184 }
	end
end
do
	local player = players["visea"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3838, 440, 678, 7180 }
	end
end
do
	local player = players["ellywoodýx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5287, 213, 297, 2612 }
	end
end
do
	local player = players["muhlix"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9374, 47, 64, 13140 }
	end
end
do
	local player = players["muhrama"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8121, 140, 190, 11027 }
	end
end
do
	local player = players["siqqx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9821, 18, 19, 14372 }
	end
end
do
	local player = players["bigbootybae"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8976, 74, 104, 12314 }
	end
end
do
	local player = players["zeckenopfer"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7177, 197, 285, 9933 }
	end
end
do
	local player = players["bearlylost"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6064, 270, 397, 8980 }
	end
end
do
	local player = players["bandalar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8857, 83, 116, 12073 }
	end
end
do
	local player = players["krautroulade"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2217, 636, 945, 3583 }
	end
end
do
	local player = players["pawpatrol"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9543, 32, 47, 13555 }
	end
end
do
	local player = players["adochso"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8728, 95, 129, 11818 }
	end
end
do
	local player = players["ripzor"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8907, 79, 111, 12200 }
	end
end
do
	local player = players["sâurôn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9463, 39, 55, 13310 }
	end
end
do
	local player = players["chicken"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9911, 10, 10, 15173 }
	end
end
do
	local player = players["ziriana"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6581, 236, 345, 9446 }
	end
end
do
	local player = players["bärakowlbama"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8032, 145, 199, 10946 }
	end
end
do
	local player = players["lolkolol"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9235, 57, 78, 12878 }
	end
end
do
	local player = players["icystorm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9124, 47, 97, 12465 }
	end
end
do
	local player = players["theodèn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8667, 71, 136, 11348 }
	end
end
do
	local player = players["otoahnacto"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5429, 241, 438, 6412 }
	end
end
do
	local player = players["diskuhtieren"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9086, 49, 104, 12273 }
	end
end
do
	local player = players["farmdudè"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7086, 154, 279, 8638 }
	end
end
do
	local player = players["hüpo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8038, 104, 185, 10294 }
	end
end
do
	local player = players["kuhramell"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1802, 478, 811, 3289 }
	end
end
do
	local player = players["facya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4210, 305, 536, 5329 }
	end
end
do
	local player = players["furtwozero"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9067, 50, 105, 12234 }
	end
end
do
	local player = players["phane"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3524, 341, 589, 4966 }
	end
end
do
	local player = players["vénex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8781, 65, 126, 11653 }
	end
end
do
	local player = players["konmuhzius"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7829, 115, 208, 9812 }
	end
end
do
	local player = players["pfotzig"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5543, 235, 428, 6612 }
	end
end
do
	local player = players["pspsps"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8933, 57, 116, 11924 }
	end
end
do
	local player = players["zonelocked"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6762, 171, 313, 8156 }
	end
end
do
	local player = players["yoshirama"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8229, 94, 165, 10664 }
	end
end
do
	local player = players["khandira"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8133, 99, 174, 10446 }
	end
end
do
	local player = players["mumpus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8095, 101, 178, 10421 }
	end
end
do
	local player = players["cenariuß"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9795, 5, 5, 87 }
	end
end
do
	local player = players["freakyzero"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4667, 95, 105, 4 }
	end
end
do
	local player = players["strohhutnami"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8499, 114, 152, 11449 }
	end
end
do
	local player = players["shytera"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5029, 262, 467, 5990 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8000, 37, 40, 12 }
	end
end
do
	local player = players["huntingtime"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9818, 3, 3, 11393 }
	end
end
do
	local player = players["aurôrrâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7060, 203, 331, 9682 }
	end
end
do
	local player = players["snipertv"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2179, 612, 949, 4654 }
	end
end
do
	local player = players["stâshly"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6201, 262, 419, 8763 }
	end
end
do
	local player = players["camillo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9461, 38, 78, 14462 }
	end
end
do
	local player = players["mmisnutsdude"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7933, 143, 249, 10823 }
	end
end
do
	local player = players["xarenia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8384, 112, 202, 11516 }
	end
end
do
	local player = players["spirithunter"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5444, 314, 503, 8072 }
	end
end
do
	local player = players["cändy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8632, 95, 178, 12103 }
	end
end
do
	local player = players["thordax"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9491, 36, 73, 14735 }
	end
end
do
	local player = players["urláub"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6550, 238, 377, 9171 }
	end
end
do
	local player = players["rimny"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9272, 51, 104, 13778 }
	end
end
do
	local player = players["khaylinn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7511, 172, 287, 10146 }
	end
end
do
	local player = players["firenzo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9199, 56, 110, 13553 }
	end
end
do
	local player = players["izakh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8792, 84, 161, 12437 }
	end
end
do
	local player = players["toomiis"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9884, 9, 21, 17003 }
	end
end
do
	local player = players["wilhèlm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9258, 52, 105, 13742 }
	end
end
do
	local player = players["shotmedown"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7918, 144, 250, 10756 }
	end
end
do
	local player = players["boozasola"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6216, 29, 42, 8628 }
	end
end
do
	local player = players["bagozwo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6622, 26, 36, 9104 }
	end
end
do
	local player = players["barzùl"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4614, 371, 588, 7509 }
	end
end
do
	local player = players["bigfatrichie"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9730, 3, 6, 15283 }
	end
end
do
	local player = players["grmgrr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8378, 13, 19, 11124 }
	end
end
do
	local player = players["richiesix"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9324, 6, 9, 14208 }
	end
end
do
	local player = players["argusmagus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8902, 51, 65, 10489 }
	end
end
do
	local player = players["nekroni"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9417, 29, 35, 11993 }
	end
end
do
	local player = players["jhinô"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7513, 114, 146, 8873 }
	end
end
do
	local player = players["drfoca"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3145, 547, 803, 6328 }
	end
end
do
	local player = players["antiwizzard"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3616, 479, 696, 7275 }
	end
end
do
	local player = players["znàx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6867, 225, 325, 11234 }
	end
end
do
	local player = players["magepewpew"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9081, 76, 96, 14660 }
	end
end
do
	local player = players["firemagex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9188, 69, 85, 15062 }
	end
end
do
	local player = players["fussel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9217, 67, 82, 15125 }
	end
end
do
	local player = players["avandur"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5861, 292, 429, 9828 }
	end
end
do
	local player = players["dpscc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8897, 88, 115, 14309 }
	end
end
do
	local player = players["zunni"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9110, 74, 93, 14749 }
	end
end
do
	local player = players["ashwings"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9381, 52, 65, 15614 }
	end
end
do
	local player = players["andorok"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9632, 30, 39, 16267 }
	end
end
do
	local player = players["redraspberry"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9352, 54, 68, 15559 }
	end
end
do
	local player = players["donkarlsen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8230, 134, 184, 13228 }
	end
end
do
	local player = players["muezzin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8017, 148, 206, 12847 }
	end
end
do
	local player = players["exwello"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8221, 135, 185, 13209 }
	end
end
do
	local player = players["végeto"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9760, 13, 15, 13991 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9961, 5, 5, 17728 }
	end
end
do
	local player = players["flereigam"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8356, 127, 171, 13382 }
	end
end
do
	local player = players["frôstâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7631, 172, 246, 12282 }
	end
end
do
	local player = players["alwinix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9304, 59, 73, 15390 }
	end
end
do
	local player = players["belliktion"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9804, 2, 4, 10196 }
	end
end
do
	local player = players["alkea"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2404, 403, 535, 93 }
	end
end
do
	local player = players["wùmpina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9744, 16, 19, 415 }
	end
end
do
	local player = players["navares"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7283, 155, 192, 221 }
	end
end
do
	local player = players["tpaladin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6885, 176, 220, 208 }
	end
end
do
	local player = players["cyrôs"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2916, 382, 499, 110 }
	end
end
do
	local player = players["mjøllnir"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6686, 186, 234, 203 }
	end
end
do
	local player = players["breezee"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8976, 63, 73, 298 }
	end
end
do
	local player = players["nôrdic"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5420, 256, 323, 168 }
	end
end
do
	local player = players["shiexz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8848, 72, 82, 288 }
	end
end
do
	local player = players["psychóó"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6907, 256, 395, 9681 }
	end
end
do
	local player = players["alixxan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2119, 417, 555, 88 }
	end
end
do
	local player = players["zycaria"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8734, 78, 90, 276 }
	end
end
do
	local player = players["hühnchenyo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1479, 442, 600, 66 }
	end
end
do
	local player = players["lischdbringa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9374, 39, 45, 336 }
	end
end
do
	local player = players["alwaysstoney"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9758, 15, 18, 420 }
	end
end
do
	local player = players["sushyx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2902, 383, 500, 108 }
	end
end
do
	local player = players["mâtrem"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9644, 22, 26, 374 }
	end
end
do
	local player = players["ruadana"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5704, 240, 303, 178 }
	end
end
do
	local player = players["innohealz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6734, 130, 180, 3973 }
	end
end
do
	local player = players["mischplatte"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8303, 68, 94, 4668 }
	end
end
do
	local player = players["schtefan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1556, 377, 547, 1522 }
	end
end
do
	local player = players["lávande"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2324, 361, 525, 2272 }
	end
end
do
	local player = players["damaris"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1977, 423, 565, 84 }
	end
end
do
	local player = players["bombâ"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9003, 87, 128, 12741 }
	end
end
do
	local player = players["bugshield"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8492, 94, 107, 261 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9882, 13, 16, 14812 }
	end
end
do
	local player = players["paypally"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5361, 387, 592, 8357 }
	end
end
do
	local player = players["henrycake"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4243, 550, 826, 6874 }
	end
end
do
	local player = players["zaliah"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4539, 503, 751, 7355 }
	end
end
do
	local player = players["rollupz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6633, 282, 430, 9433 }
	end
end
do
	local player = players["tankpflaster"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9246, 72, 97, 13177 }
	end
end
do
	local player = players["wondérwoman"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9630, 15, 22, 6990 }
	end
end
do
	local player = players["firelead"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5255, 187, 261, 3573 }
	end
end
do
	local player = players["sêrwantes"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7912, 173, 267, 10771 }
	end
end
do
	local player = players["niggelsn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9929, 8, 10, 15281 }
	end
end
do
	local player = players["rikary"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5861, 231, 292, 180 }
	end
end
do
	local player = players["farodín"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8704, 50, 72, 4972 }
	end
end
do
	local player = players["watschlicht"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8212, 72, 99, 4567 }
	end
end
do
	local player = players["tankeêeêeêeê"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8285, 69, 95, 4636 }
	end
end
do
	local player = players["shindar"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7162, 232, 363, 9911 }
	end
end
do
	local player = players["niggels"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9356, 66, 83, 13321 }
	end
end
do
	local player = players["rìga"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8784, 100, 156, 12328 }
	end
end
do
	local player = players["allianz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9537, 48, 60, 13660 }
	end
end
do
	local player = players["vermythór"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4033, 232, 328, 3326 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8636, 112, 178, 11954 }
	end
end
do
	local player = players["xiaolü"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9349, 67, 84, 13305 }
	end
end
do
	local player = players["zkittlèz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7644, 73, 83, 195 }
	end
end
do
	local player = players["milchreitz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6472, 263, 394, 8582 }
	end
end
do
	local player = players["schokipriest"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7126, 87, 101, 186 }
	end
end
do
	local player = players["mêxxina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9023, 30, 35, 250 }
	end
end
do
	local player = players["leshy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8736, 38, 45, 240 }
	end
end
do
	local player = players["dalisa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8218, 56, 63, 210 }
	end
end
do
	local player = players["suanmeitang"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6609, 103, 119, 178 }
	end
end
do
	local player = players["quadron"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8960, 76, 119, 11870 }
	end
end
do
	local player = players["sômbrâ"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6322, 112, 129, 170 }
	end
end
do
	local player = players["lithumi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9770, 9, 9, 383 }
	end
end
do
	local player = players["simmi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6810, 98, 112, 182 }
	end
end
do
	local player = players["yoshiako"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5957, 37, 39, 158 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7753, 163, 259, 10002 }
	end
end
do
	local player = players["tmix"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4971, 151, 176, 148 }
	end
end
do
	local player = players["sicksick"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6383, 33, 35, 165 }
	end
end
do
	local player = players["erivan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1868, 221, 284, 81 }
	end
end
do
	local player = players["geìsteskrank"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9461, 44, 61, 12970 }
	end
end
do
	local player = players["kochstudio"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6158, 282, 429, 8287 }
	end
end
do
	local player = players["ceasy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9569, 36, 49, 13168 }
	end
end
do
	local player = players["zargat"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6454, 264, 396, 8558 }
	end
end
do
	local player = players["outbreak"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9066, 70, 105, 12246 }
	end
end
do
	local player = players["noxinâ"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4648, 405, 607, 7117 }
	end
end
do
	local player = players["rlin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6346, 273, 408, 8453 }
	end
end
do
	local player = players["fylax"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9749, 22, 29, 13635 }
	end
end
do
	local player = players["kaiden"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3933, 519, 779, 6022 }
	end
end
do
	local player = players["fakeheal"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9885, 5, 5, 720 }
	end
end
do
	local player = players["nudemodeqtx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9479, 43, 59, 13025 }
	end
end
do
	local player = players["meridil"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5943, 297, 453, 8076 }
	end
end
do
	local player = players["bllink"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9417, 47, 66, 12878 }
	end
end
do
	local player = players["yoshiyuki"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8830, 12, 12, 241 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9910, 10, 11, 14183 }
	end
end
do
	local player = players["stutnspalter"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5826, 306, 466, 8030 }
	end
end
do
	local player = players["bagorini"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3218, 187, 237, 115 }
	end
end
do
	local player = players["rubiná"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9767, 21, 27, 13694 }
	end
end
do
	local player = players["prophetin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8393, 117, 180, 10958 }
	end
end
do
	local player = players["tyruna"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7933, 150, 236, 10332 }
	end
end
do
	local player = players["synnora"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9013, 73, 111, 12092 }
	end
end
do
	local player = players["neihra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6813, 232, 356, 8893 }
	end
end
do
	local player = players["markusfreund"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7627, 137, 255, 11841 }
	end
end
do
	local player = players["gîft"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7539, 142, 262, 11755 }
	end
end
do
	local player = players["kampfwumme"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6265, 215, 367, 10667 }
	end
end
do
	local player = players["dodokay"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9423, 40, 54, 15006 }
	end
end
do
	local player = players["suzann"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8202, 104, 189, 12757 }
	end
end
do
	local player = players["sapsori"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7382, 151, 278, 11584 }
	end
end
do
	local player = players["ubichanibys"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9304, 48, 65, 14744 }
	end
end
do
	local player = players["machetenphil"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5567, 255, 425, 9952 }
	end
end
do
	local player = players["asycs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8325, 97, 159, 13197 }
	end
end
do
	local player = players["edelschurke"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6824, 183, 323, 11093 }
	end
end
do
	local player = players["nierenpikser"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2257, 552, 867, 4095 }
	end
end
do
	local player = players["samely"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8010, 115, 208, 12554 }
	end
end
do
	local player = players["bongobernd"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8394, 93, 155, 13259 }
	end
end
do
	local player = players["funspec"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8377, 94, 156, 13253 }
	end
end
do
	local player = players["díggson"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3022, 507, 797, 5484 }
	end
end
do
	local player = players["bazzen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7138, 165, 298, 11399 }
	end
end
do
	local player = players["hazro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9249, 52, 70, 14679 }
	end
end
do
	local player = players["sasanna"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3971, 413, 662, 7205 }
	end
end
do
	local player = players["syntrix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7592, 139, 258, 11817 }
	end
end
do
	local player = players["klospülung"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3236, 491, 768, 5871 }
	end
end
do
	local player = players["meistab"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7312, 155, 284, 11502 }
	end
end
do
	local player = players["vaterwøtan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9010, 63, 92, 14212 }
	end
end
do
	local player = players["huberts"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8586, 82, 132, 13567 }
	end
end
do
	local player = players["shamali"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1852, 309, 404, 4 }
	end
end
do
	local player = players["rundrügg"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8867, 52, 71, 12786 }
	end
end
do
	local player = players["anamnesis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2999, 325, 460, 6105 }
	end
end
do
	local player = players["schamageddon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9239, 34, 48, 13647 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 224, 371, 482, 0 }
	end
end
do
	local player = players["kainalu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4286, 217, 292, 14 }
	end
end
do
	local player = players["tashany"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9078, 41, 58, 13330 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1443, 325, 422, 3 }
	end
end
do
	local player = players["starflux"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7564, 105, 153, 10236 }
	end
end
do
	local player = players["menørex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7055, 130, 183, 9551 }
	end
end
do
	local player = players["orkdruide"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6327, 167, 228, 8926 }
	end
end
do
	local player = players["innoshamy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7120, 127, 179, 9616 }
	end
end
do
	local player = players["stormshaman"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8361, 71, 104, 11548 }
	end
end
do
	local player = players["raschtul"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8706, 59, 81, 12199 }
	end
end
do
	local player = players["shallah"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7541, 106, 154, 10234 }
	end
end
do
	local player = players["thrukasch"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8244, 76, 111, 11473 }
	end
end
do
	local player = players["yonaschama"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3132, 311, 439, 6376 }
	end
end
do
	local player = players["neytîri"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7023, 132, 185, 9540 }
	end
end
do
	local player = players["gauloises"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6230, 172, 234, 8812 }
	end
end
do
	local player = players["miorny"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9132, 26, 41, 12807 }
	end
end
do
	local player = players["cupcâke"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6855, 91, 146, 10369 }
	end
end
do
	local player = players["nossì"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9653, 12, 17, 13908 }
	end
end
do
	local player = players["haagl"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 996, 342, 444, 2 }
	end
end
do
	local player = players["jackycoola"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2699, 251, 414, 5241 }
	end
end
do
	local player = players["liniil"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6085, 149, 198, 45 }
	end
end
do
	local player = players["mfrog"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9822, 9, 12, 16490 }
	end
end
do
	local player = players["rendol"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2646, 279, 371, 6 }
	end
end
do
	local player = players["dangerthings"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7785, 86, 110, 340 }
	end
end
do
	local player = players["astrene"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7317, 105, 133, 183 }
	end
end
do
	local player = players["shamin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1534, 321, 418, 3 }
	end
end
do
	local player = players["skornak"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8407, 69, 101, 11697 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1463, 324, 421, 3 }
	end
end
do
	local player = players["sterbehüfe"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2210, 394, 556, 4500 }
	end
end
do
	local player = players["swîffer"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3968, 229, 304, 12 }
	end
end
do
	local player = players["newoi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5906, 187, 254, 8552 }
	end
end
do
	local player = players["kuraokami"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7541, 96, 122, 226 }
	end
end
do
	local player = players["semegal"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7378, 102, 130, 193 }
	end
end
do
	local player = players["tumaria"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9740, 9, 13, 14162 }
	end
end
do
	local player = players["elemenemu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6861, 139, 195, 9394 }
	end
end
do
	local player = players["desertéd"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4339, 215, 290, 15 }
	end
end
do
	local player = players["pachuist"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9223, 35, 49, 13574 }
	end
end
do
	local player = players["gedak"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5488, 133, 209, 9348 }
	end
end
do
	local player = players["zarbo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1958, 305, 399, 4 }
	end
end
do
	local player = players["aerith"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1301, 332, 429, 3 }
	end
end
do
	local player = players["thoraiib"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8063, 68, 99, 10760 }
	end
end
do
	local player = players["dotgott"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8439, 53, 80, 11582 }
	end
end
do
	local player = players["scire"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4150, 200, 297, 6574 }
	end
end
do
	local player = players["fisthex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7470, 87, 129, 9965 }
	end
end
do
	local player = players["genüsslich"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3261, 386, 589, 5336 }
	end
end
do
	local player = players["darzuul"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7767, 77, 114, 10344 }
	end
end
do
	local player = players["yakarûe"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8360, 56, 84, 11509 }
	end
end
do
	local player = players["nihilvexion"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8581, 65, 119, 11204 }
	end
end
do
	local player = players["findonia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4979, 238, 352, 7992 }
	end
end
do
	local player = players["kraim"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5711, 154, 218, 8254 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9424, 27, 45, 13701 }
	end
end
do
	local player = players["shadowkillaa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2858, 274, 410, 4898 }
	end
end
do
	local player = players["keô"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9002, 46, 86, 12190 }
	end
end
do
	local player = players["andromalíus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9229, 29, 40, 13524 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8758, 57, 106, 11637 }
	end
end
do
	local player = players["asmodeûs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7982, 92, 157, 10418 }
	end
end
do
	local player = players["gabrielburns"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8958, 48, 88, 12082 }
	end
end
do
	local player = players["tassi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9157, 39, 66, 13013 }
	end
end
do
	local player = players["valeviah"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2984, 262, 390, 5115 }
	end
end
do
	local player = players["zaras"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8617, 46, 71, 12077 }
	end
end
do
	local player = players["merydol"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2310, 437, 681, 3781 }
	end
end
do
	local player = players["saltydots"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7384, 119, 190, 9914 }
	end
end
do
	local player = players["miriandâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8847, 53, 101, 11784 }
	end
end
do
	local player = players["felka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7716, 104, 171, 10265 }
	end
end
do
	local player = players["metatronn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9742, 14, 19, 15056 }
	end
end
do
	local player = players["mâlâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9069, 43, 78, 12489 }
	end
end
do
	local player = players["reptøxia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7802, 21, 36, 8659 }
	end
end
do
	local player = players["beledros"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5579, 206, 310, 8480 }
	end
end
do
	local player = players["nøs"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9670, 4, 7, 12191 }
	end
end
do
	local player = players["kenpachí"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5200, 25, 32, 7354 }
	end
end
do
	local player = players["glarin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8008, 190, 299, 12472 }
	end
end
do
	local player = players["senfeier"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7620, 233, 368, 11781 }
	end
end
do
	local player = players["wendeta"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9351, 82, 101, 15921 }
	end
end
do
	local player = players["epçs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9799, 29, 32, 17568 }
	end
end
do
	local player = players["zedseroya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8021, 191, 300, 12472 }
	end
end
do
	local player = players["watschrage"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9400, 4, 6, 11238 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8437, 157, 242, 13493 }
	end
end
do
	local player = players["ryomaha"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6044, 397, 611, 9863 }
	end
end
do
	local player = players["farlog"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4501, 555, 849, 8454 }
	end
end
do
	local player = players["warcrimex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9183, 100, 127, 15476 }
	end
end
do
	local player = players["dingoosa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6952, 307, 471, 10802 }
	end
end
do
	local player = players["wuttutmirgut"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7127, 287, 444, 11054 }
	end
end
do
	local player = players["pishro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8431, 158, 243, 13471 }
	end
end
do
	local player = players["kassierer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9747, 36, 40, 17337 }
	end
end
do
	local player = players["bubensahne"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9715, 40, 45, 16967 }
	end
end
do
	local player = players["voodoocharge"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8534, 149, 227, 13708 }
	end
end
do
	local player = players["xeywia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9981, 4, 4, 18908 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9237, 17, 21, 4326 }
	end
end
do
	local player = players["slaîne"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9974, 5, 5, 18813 }
	end
end
do
	local player = players["nøvicron"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2495, 842, 1349, 5164 }
	end
end
do
	local player = players["mczaet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8787, 131, 188, 14497 }
	end
end
do
	local player = players["maelkashishi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3162, 746, 1188, 6544 }
	end
end
do
	local player = players["disconsolate"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5590, 443, 681, 9436 }
	end
end
do
	local player = players["lancee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7594, 236, 372, 11748 }
	end
end
do
	local player = players["jörgsaronn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4981, 509, 775, 8848 }
	end
end
do
	local player = players["xalyna"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9241, 93, 118, 15608 }
	end
end
do
	local player = players["flinn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8230, 176, 274, 12983 }
	end
end
do
	local player = players["thoraiss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6505, 350, 540, 10292 }
	end
end
do
	local player = players["crownseeker"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9734, 38, 42, 17316 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
