-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "voa"
local chunkStartIndex = 1
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["rarität"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9985, 2, 2, 18274 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 10000, 1, 1, 19629 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 10000, 1, 1, 18710 }
	end
end
do
	local player = players["runenmacht"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9954, 3, 5, 17055 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9919, 4, 5, 16243 }
	end
end
do
	local player = players["dorli"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9931, 4, 6, 16860 }
	end
end
do
	local player = players["marikø"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9908, 5, 8, 16622 }
	end
end
do
	local player = players["bee"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9632, 17, 25, 13116 }
	end
end
do
	local player = players["dörli"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9885, 6, 10, 16056 }
	end
end
do
	local player = players["ayrez"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9712, 13, 21, 13421 }
	end
end
do
	local player = players["readyjack"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6492, 159, 229, 2872 }
	end
end
do
	local player = players["hákuren"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9448, 25, 41, 11451 }
	end
end
do
	local player = players["barabbass"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7123, 129, 188, 3187 }
	end
end
do
	local player = players["cholerra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4736, 332, 520, 8860 }
	end
end
do
	local player = players["frizzboom"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8069, 85, 135, 3843 }
	end
end
do
	local player = players["schrottgott"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9207, 32, 40, 12258 }
	end
end
do
	local player = players["skullcrushêr"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9816, 9, 15, 15262 }
	end
end
do
	local player = players["châlmers"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9747, 12, 18, 13812 }
	end
end
do
	local player = players["whitêghøst"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9494, 23, 36, 11744 }
	end
end
do
	local player = players["jackpack"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5170, 300, 474, 9228 }
	end
end
do
	local player = players["aìr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9980, 2, 2, 17995 }
	end
end
do
	local player = players["snowypeak"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4270, 197, 268, 7845 }
	end
end
do
	local player = players["premiumdaddy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9451, 22, 28, 13039 }
	end
end
do
	local player = players["kirïfrost"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9268, 30, 37, 12389 }
	end
end
do
	local player = players["frostbull"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9512, 20, 25, 13308 }
	end
end
do
	local player = players["deepdarkness"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9952, 4, 6, 17307 }
	end
end
do
	local player = players["ürth"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9959, 3, 3, 16684 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9528, 31, 47, 14792 }
	end
end
do
	local player = players["keitolg"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9651, 24, 35, 15249 }
	end
end
do
	local player = players["dablé"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7770, 98, 150, 3612 }
	end
end
do
	local player = players["galasdk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4897, 317, 498, 9044 }
	end
end
do
	local player = players["yujirohanma"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9487, 33, 51, 14702 }
	end
end
do
	local player = players["raiders"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9839, 8, 14, 15390 }
	end
end
do
	local player = players["whayne"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6704, 209, 322, 10604 }
	end
end
do
	local player = players["avisionqt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9415, 39, 58, 14458 }
	end
end
do
	local player = players["undrcvrpase"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9822, 12, 20, 15901 }
	end
end
do
	local player = players["kuroichi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9158, 57, 83, 13908 }
	end
end
do
	local player = players["therrac"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9935, 5, 8, 16943 }
	end
end
do
	local player = players["likeezz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9819, 7, 10, 15279 }
	end
end
do
	local player = players["rokkyy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9725, 18, 28, 15485 }
	end
end
do
	local player = players["wâsti"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9620, 27, 38, 15165 }
	end
end
do
	local player = players["rishtara"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9127, 60, 86, 13830 }
	end
end
do
	local player = players["antiengel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6200, 174, 248, 2811 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8789, 83, 119, 13091 }
	end
end
do
	local player = players["yaru"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9806, 13, 21, 15894 }
	end
end
do
	local player = players["kiyotaka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3446, 296, 427, 2308 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4112, 413, 652, 7693 }
	end
end
do
	local player = players["blinkeydk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6940, 196, 299, 10846 }
	end
end
do
	local player = players["rdo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9343, 45, 65, 14298 }
	end
end
do
	local player = players["coldicetea"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9476, 34, 52, 14680 }
	end
end
do
	local player = players["spezisto"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7659, 151, 229, 11605 }
	end
end
do
	local player = players["enjoý"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2562, 281, 419, 5029 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9969, 3, 4, 17486 }
	end
end
do
	local player = players["redeemêr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9209, 53, 78, 13945 }
	end
end
do
	local player = players["neglectio"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3108, 312, 449, 2259 }
	end
end
do
	local player = players["jixxy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7569, 107, 159, 3501 }
	end
end
do
	local player = players["intoodeep"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8943, 73, 104, 13334 }
	end
end
do
	local player = players["tieneun"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9797, 8, 11, 15175 }
	end
end
do
	local player = players["ryomaa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5719, 266, 419, 9739 }
	end
end
do
	local player = players["nuadosk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4696, 336, 528, 8786 }
	end
end
do
	local player = players["kathalia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9536, 26, 58, 13984 }
	end
end
do
	local player = players["pøwl"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9856, 10, 14, 15838 }
	end
end
do
	local player = players["bellony"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9306, 52, 73, 13033 }
	end
end
do
	local player = players["sosuke"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9923, 8, 9, 15298 }
	end
end
do
	local player = players["firstdøwn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9634, 29, 39, 13762 }
	end
end
do
	local player = players["ølympîa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9846, 15, 17, 14569 }
	end
end
do
	local player = players["bhullwhêyy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9300, 13, 15, 25 }
	end
end
do
	local player = players["yeat"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9932, 7, 8, 15326 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9600, 8, 9, 52 }
	end
end
do
	local player = players["dragøran"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9836, 16, 18, 14519 }
	end
end
do
	local player = players["skyfallx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9254, 55, 76, 12947 }
	end
end
do
	local player = players["beibi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9913, 9, 10, 15219 }
	end
end
do
	local player = players["skriptxjk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 10000, 1, 1, 16162 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4600, 99, 109, 4 }
	end
end
do
	local player = players["ruskó"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9479, 38, 55, 13383 }
	end
end
do
	local player = players["zheril"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4620, 291, 516, 5597 }
	end
end
do
	local player = players["muhlinäx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9527, 34, 51, 13487 }
	end
end
do
	local player = players["superbowl"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9865, 13, 15, 14863 }
	end
end
do
	local player = players["puschenvieh"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9570, 31, 47, 13595 }
	end
end
do
	local player = players["animantur"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9981, 3, 3, 15792 }
	end
end
do
	local player = players["pîxxîe"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9662, 26, 36, 13883 }
	end
end
do
	local player = players["airshred"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9369, 35, 76, 13325 }
	end
end
do
	local player = players["schutzwolf"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9967, 4, 4, 16593 }
	end
end
do
	local player = players["eeyore"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9481, 29, 64, 13876 }
	end
end
do
	local player = players["miezel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9834, 12, 16, 15823 }
	end
end
do
	local player = players["centralina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9911, 8, 9, 16149 }
	end
end
do
	local player = players["mietsel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9789, 13, 20, 15309 }
	end
end
do
	local player = players["woodiiee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9945, 6, 6, 16340 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6100, 71, 79, 6 }
	end
end
do
	local player = players["tubalcain"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9722, 16, 27, 15164 }
	end
end
do
	local player = players["trayzishiftr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9989, 2, 2, 17498 }
	end
end
do
	local player = players["schnurbèrt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7774, 121, 216, 9745 }
	end
end
do
	local player = players["ferocity"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9462, 30, 67, 13796 }
	end
end
do
	local player = players["biêr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9978, 3, 3, 17315 }
	end
end
do
	local player = players["vertraumir"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9933, 7, 7, 16300 }
	end
end
do
	local player = players["darquisex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9332, 37, 79, 12948 }
	end
end
do
	local player = players["nhoernchen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8831, 64, 124, 11733 }
	end
end
do
	local player = players["motrokko"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9499, 28, 62, 13928 }
	end
end
do
	local player = players["parviflora"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 10000, 1, 1, 18252 }
	end
end
do
	local player = players["ignore"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8746, 94, 131, 11843 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8887, 61, 120, 11876 }
	end
end
do
	local player = players["purrpurr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9740, 15, 26, 15199 }
	end
end
do
	local player = players["dookie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9956, 5, 5, 16356 }
	end
end
do
	local player = players["kôzue"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9209, 59, 79, 12856 }
	end
end
do
	local player = players["primrøse"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9056, 50, 105, 12150 }
	end
end
do
	local player = players["lunárá"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9666, 19, 34, 14928 }
	end
end
do
	local player = players["erdbärbaum"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5176, 261, 469, 6082 }
	end
end
do
	local player = players["jehala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5294, 332, 489, 8373 }
	end
end
do
	local player = players["crookshanks"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7236, 150, 275, 8815 }
	end
end
do
	local player = players["kakeh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9767, 14, 22, 15271 }
	end
end
do
	local player = players["chimæra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7588, 131, 240, 9485 }
	end
end
do
	local player = players["tiia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7124, 156, 283, 8689 }
	end
end
do
	local player = players["boomkiin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 2128, 668, 997, 3439 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9629, 21, 43, 14706 }
	end
end
do
	local player = players["feralbuck"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7310, 146, 271, 8952 }
	end
end
do
	local player = players["eminenze"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9128, 48, 101, 12343 }
	end
end
do
	local player = players["riverd"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4304, 308, 541, 5380 }
	end
end
do
	local player = players["lisley"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9344, 50, 69, 13086 }
	end
end
do
	local player = players["tarramis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9431, 43, 60, 13224 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9950, 2, 2, 160 }
	end
end
do
	local player = players["xantthorr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4991, 271, 481, 5968 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9900, 3, 3, 111 }
	end
end
do
	local player = players["chueli"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9500, 10, 11, 37 }
	end
end
do
	local player = players["baumkröne"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9450, 11, 12, 28 }
	end
end
do
	local player = players["nappolion"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9550, 9, 10, 43 }
	end
end
do
	local player = players["evang"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4578, 411, 613, 7399 }
	end
end
do
	local player = players["drúdix"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2100, 141, 159, 2 }
	end
end
do
	local player = players["greenorina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9091, 50, 105, 12257 }
	end
end
do
	local player = players["myrthia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8200, 35, 37, 12 }
	end
end
do
	local player = players["nowolas"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5400, 85, 93, 4 }
	end
end
do
	local player = players["druidhilde"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6403, 255, 374, 9316 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8750, 24, 26, 19 }
	end
end
do
	local player = players["blinkeydru"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6679, 180, 330, 8051 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1850, 146, 164, 2 }
	end
end
do
	local player = players["tââvi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9200, 15, 17, 24 }
	end
end
do
	local player = players["hââgl"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1894, 474, 805, 3458 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8450, 30, 32, 16 }
	end
end
do
	local player = players["rubîksmind"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5455, 246, 446, 6430 }
	end
end
do
	local player = players["selenabowmez"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 10000, 1, 1, 19992 }
	end
end
do
	local player = players["nodistance"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9177, 59, 117, 13503 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9907, 2, 2, 17696 }
	end
end
do
	local player = players["treffsichair"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 10000, 1, 1, 21358 }
	end
end
do
	local player = players["ticketisraus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5560, 314, 501, 8135 }
	end
end
do
	local player = players["arbutus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9830, 13, 32, 16030 }
	end
end
do
	local player = players["spika"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9688, 23, 50, 15321 }
	end
end
do
	local player = players["kapohunt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7362, 187, 312, 9926 }
	end
end
do
	local player = players["garto"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9986, 2, 4, 19693 }
	end
end
do
	local player = players["schönramer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9078, 66, 129, 13062 }
	end
end
do
	local player = players["gariu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9957, 4, 7, 18704 }
	end
end
do
	local player = players["gârto"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9929, 6, 16, 17948 }
	end
end
do
	local player = players["kurata"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5163, 342, 543, 7866 }
	end
end
do
	local player = players["onralock"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9972, 3, 5, 19046 }
	end
end
do
	local player = players["bagorin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9912, 2, 2, 13562 }
	end
end
do
	local player = players["yamali"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9617, 28, 59, 15033 }
	end
end
do
	local player = players["néijth"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3730, 443, 711, 6820 }
	end
end
do
	local player = players["judíka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9844, 12, 29, 16233 }
	end
end
do
	local player = players["galapew"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1831, 669, 1039, 3910 }
	end
end
do
	local player = players["horaisen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9915, 7, 17, 17880 }
	end
end
do
	local player = players["houseknecht"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7390, 185, 309, 9991 }
	end
end
do
	local player = players["eiré"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9674, 24, 52, 15196 }
	end
end
do
	local player = players["ohoernchen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9390, 44, 92, 14003 }
	end
end
do
	local player = players["eminencê"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8426, 112, 201, 11541 }
	end
end
do
	local player = players["zuclo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7504, 177, 295, 10137 }
	end
end
do
	local player = players["kamilshot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9901, 8, 18, 17596 }
	end
end
do
	local player = players["galatea"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9376, 45, 93, 13983 }
	end
end
do
	local player = players["wodkatonix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8681, 94, 176, 12199 }
	end
end
do
	local player = players["fallinlove"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8652, 96, 180, 12161 }
	end
end
do
	local player = players["gárto"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8738, 90, 168, 12341 }
	end
end
do
	local player = players["drobovic"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9625, 4, 7, 15241 }
	end
end
do
	local player = players["kirïlegacy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8625, 12, 17, 11661 }
	end
end
do
	local player = players["medhiva"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9801, 11, 13, 14634 }
	end
end
do
	local player = players["talyrya"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8972, 50, 63, 10551 }
	end
end
do
	local player = players["xelforkuna"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9851, 9, 10, 15207 }
	end
end
do
	local player = players["ihrnoobs"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9519, 25, 30, 12231 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9081, 77, 99, 14620 }
	end
end
do
	local player = players["heldenhonk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9967, 3, 3, 17406 }
	end
end
do
	local player = players["hondri"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9887, 13, 13, 17460 }
	end
end
do
	local player = players["welovesölden"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9597, 35, 44, 16141 }
	end
end
do
	local player = players["hobbymagus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 10000, 1, 1, 18940 }
	end
end
do
	local player = players["kéloda"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9983, 2, 2, 18143 }
	end
end
do
	local player = players["òlympia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4540, 401, 583, 8483 }
	end
end
do
	local player = players["muschelsaftt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9526, 40, 50, 16054 }
	end
end
do
	local player = players["loderliese"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9540, 40, 50, 16054 }
	end
end
do
	local player = players["unodostrayz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9794, 22, 23, 16913 }
	end
end
do
	local player = players["nokiaketchup"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9587, 36, 45, 16123 }
	end
end
do
	local player = players["zeekx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9503, 44, 54, 16001 }
	end
end
do
	local player = players["pdace"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8171, 140, 196, 13082 }
	end
end
do
	local player = players["tüvmage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9146, 73, 92, 14788 }
	end
end
do
	local player = players["iksdoppeld"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1595, 680, 1033, 3209 }
	end
end
do
	local player = players["enviouzly"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3038, 575, 854, 6112 }
	end
end
do
	local player = players["pyrotechník"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8105, 145, 203, 12921 }
	end
end
do
	local player = players["karlakawumna"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9578, 37, 46, 16099 }
	end
end
do
	local player = players["wishmopp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8827, 93, 126, 14187 }
	end
end
do
	local player = players["lunaiiya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9062, 78, 101, 14587 }
	end
end
do
	local player = players["vyndyra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9700, 28, 33, 16505 }
	end
end
do
	local player = players["cheminée"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5141, 352, 519, 9095 }
	end
end
do
	local player = players["blizzlike"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7984, 122, 148, 248 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9912, 6, 6, 8777 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9992, 2, 2, 16170 }
	end
end
do
	local player = players["meringes"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9300, 45, 52, 324 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9235, 31, 45, 5794 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9335, 70, 89, 13270 }
	end
end
do
	local player = players["yuukì"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7147, 167, 209, 219 }
	end
end
do
	local player = players["mcbubbel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8916, 69, 80, 295 }
	end
end
do
	local player = players["lysitea"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6463, 197, 244, 195 }
	end
end
do
	local player = players["gayzisto"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9808, 13, 15, 442 }
	end
end
do
	local player = players["daesung"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9805, 9, 12, 8015 }
	end
end
do
	local player = players["stevepaladin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5089, 283, 359, 159 }
	end
end
do
	local player = players["tamallia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6982, 176, 221, 215 }
	end
end
do
	local player = players["gnoin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8820, 76, 87, 286 }
	end
end
do
	local player = players["careese"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8326, 105, 123, 257 }
	end
end
do
	local player = players["yodashi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8750, 50, 72, 5001 }
	end
end
do
	local player = players["helön"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7627, 142, 174, 234 }
	end
end
do
	local player = players["emerlis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8628, 87, 101, 273 }
	end
end
do
	local player = players["hystería"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5223, 414, 633, 8183 }
	end
end
do
	local player = players["paraxis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9095, 59, 67, 305 }
	end
end
do
	local player = players["vkskill"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 10000, 1, 1, 9776 }
	end
end
do
	local player = players["vkskîllqt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7531, 147, 181, 232 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9965, 3, 3, 9349 }
	end
end
do
	local player = players["vkskîll"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9929, 5, 5, 8791 }
	end
end
do
	local player = players["rankøne"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5158, 279, 354, 162 }
	end
end
do
	local player = players["op"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9947, 4, 4, 8858 }
	end
end
do
	local player = players["roadtank"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9894, 7, 7, 8643 }
	end
end
do
	local player = players["protpalguide"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9005, 40, 60, 5350 }
	end
end
do
	local player = players["müllkörper"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8442, 64, 89, 4760 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3447, 696, 1072, 5584 }
	end
end
do
	local player = players["tieming"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6845, 184, 231, 208 }
	end
end
do
	local player = players["reinrudern"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7982, 86, 115, 4464 }
	end
end
do
	local player = players["ârîáná"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6973, 123, 172, 4024 }
	end
end
do
	local player = players["finallight"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9464, 22, 32, 6375 }
	end
end
do
	local player = players["wingz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8957, 93, 139, 12567 }
	end
end
do
	local player = players["traagetasche"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9770, 11, 14, 7600 }
	end
end
do
	local player = players["paradan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9864, 16, 19, 14669 }
	end
end
do
	local player = players["protexin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9773, 25, 31, 14287 }
	end
end
do
	local player = players["daesungw"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9788, 10, 13, 7612 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7218, 239, 369, 9974 }
	end
end
do
	local player = players["perssiina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9668, 14, 21, 7053 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9849, 18, 21, 14470 }
	end
end
do
	local player = players["chaiinzx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9788, 24, 29, 14299 }
	end
end
do
	local player = players["emìnenz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9342, 69, 88, 13277 }
	end
end
do
	local player = players["artria"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8807, 77, 88, 286 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9515, 20, 30, 6587 }
	end
end
do
	local player = players["biscuitoliva"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9643, 23, 27, 373 }
	end
end
do
	local player = players["seagul"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9260, 30, 43, 5822 }
	end
end
do
	local player = players["sarmad"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8262, 148, 234, 11253 }
	end
end
do
	local player = players["washedupret"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9902, 11, 14, 14931 }
	end
end
do
	local player = players["wasti"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9970, 5, 5, 15623 }
	end
end
do
	local player = players["meriskâ"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 1824, 443, 597, 80 }
	end
end
do
	local player = players["kolbenfressa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8697, 82, 96, 275 }
	end
end
do
	local player = players["soulliê"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7188, 164, 206, 219 }
	end
end
do
	local player = players["tiewatz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8987, 91, 135, 12629 }
	end
end
do
	local player = players["elturax"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9924, 9, 11, 15217 }
	end
end
do
	local player = players["sdkbuffen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9133, 35, 51, 5562 }
	end
end
do
	local player = players["gonathira"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9728, 30, 37, 14096 }
	end
end
do
	local player = players["ariovistt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9982, 2, 2, 9478 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9796, 23, 28, 14320 }
	end
end
do
	local player = players["koena"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8560, 91, 106, 267 }
	end
end
do
	local player = players["bubbleoffear"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7575, 99, 138, 4260 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4726, 480, 730, 7657 }
	end
end
do
	local player = players["darthmôre"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5542, 258, 326, 173 }
	end
end
do
	local player = players["jackile"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8980, 41, 61, 5349 }
	end
end
do
	local player = players["tarnakor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5823, 171, 237, 3746 }
	end
end
do
	local player = players["rodgerrigo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9615, 41, 52, 13828 }
	end
end
do
	local player = players["retrified"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3474, 695, 1071, 5628 }
	end
end
do
	local player = players["zyalana"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2798, 763, 1178, 4533 }
	end
end
do
	local player = players["annikara"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4704, 485, 738, 7621 }
	end
end
do
	local player = players["tenerîffa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7956, 124, 150, 247 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9501, 53, 67, 13543 }
	end
end
do
	local player = players["shaddyy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9972, 2, 2, 2463 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9670, 31, 39, 13392 }
	end
end
do
	local player = players["karpfên"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7436, 192, 300, 9657 }
	end
end
do
	local player = players["naatalya"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7806, 71, 80, 197 }
	end
end
do
	local player = players["disturbia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9878, 13, 15, 14138 }
	end
end
do
	local player = players["discopeppen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7778, 72, 81, 196 }
	end
end
do
	local player = players["ilystra"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8938, 32, 37, 247 }
	end
end
do
	local player = players["egirlqt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6222, 118, 137, 168 }
	end
end
do
	local player = players["abofalle"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8667, 42, 49, 235 }
	end
end
do
	local player = players["deinproblem"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7426, 26, 27, 183 }
	end
end
do
	local player = players["hykrõs"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9070, 72, 108, 12230 }
	end
end
do
	local player = players["klexiri"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4752, 49, 54, 137 }
	end
end
do
	local player = players["watschangel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4851, 48, 53, 138 }
	end
end
do
	local player = players["elsupafiasko"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9861, 14, 17, 14075 }
	end
end
do
	local player = players["blursed"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7723, 24, 24, 200 }
	end
end
do
	local player = players["mythicplus"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9705, 27, 35, 13456 }
	end
end
do
	local player = players["hiereia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8658, 101, 160, 11312 }
	end
end
do
	local player = players["schinden"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7530, 185, 289, 9764 }
	end
end
do
	local player = players["shîwa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9661, 32, 40, 13382 }
	end
end
do
	local player = players["helleraffli"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9991, 2, 2, 15118 }
	end
end
do
	local player = players["maveriks"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4952, 389, 582, 7436 }
	end
end
do
	local player = players["øbey"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9896, 12, 13, 14158 }
	end
end
do
	local player = players["dotzblitz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 10000, 1, 1, 15311 }
	end
end
do
	local player = players["fggtboyx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8765, 93, 148, 11457 }
	end
end
do
	local player = players["lyberty"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9679, 30, 38, 13429 }
	end
end
do
	local player = players["pairin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7651, 176, 278, 9864 }
	end
end
do
	local player = players["kirugiru"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4498, 429, 638, 6887 }
	end
end
do
	local player = players["kurokawa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9952, 2, 2, 14332 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9937, 6, 7, 17187 }
	end
end
do
	local player = players["berzayna"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9636, 5, 9, 13378 }
	end
end
do
	local player = players["ramoxz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7588, 28, 42, 10512 }
	end
end
do
	local player = players["metatricks"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9979, 3, 3, 17427 }
	end
end
do
	local player = players["reinlusten"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 10000, 1, 1, 18145 }
	end
end
do
	local player = players["ereon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9685, 26, 31, 15700 }
	end
end
do
	local player = players["shorf"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9884, 10, 12, 16436 }
	end
end
do
	local player = players["demigød"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9579, 31, 41, 15428 }
	end
end
do
	local player = players["pilikas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9422, 41, 56, 14997 }
	end
end
do
	local player = players["vuux"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8896, 70, 106, 14036 }
	end
end
do
	local player = players["dìggson"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9769, 19, 23, 15962 }
	end
end
do
	local player = players["iwek"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9285, 50, 69, 14722 }
	end
end
do
	local player = players["suspirja"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9653, 27, 34, 15617 }
	end
end
do
	local player = players["sálzig"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9947, 5, 6, 17223 }
	end
end
do
	local player = players["shivshow"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9916, 8, 9, 17047 }
	end
end
do
	local player = players["knivez"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9558, 32, 43, 15414 }
	end
end
do
	local player = players["laymessecrog"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9821, 15, 18, 16170 }
	end
end
do
	local player = players["sâlzig"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3720, 459, 725, 6750 }
	end
end
do
	local player = players["asard"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9905, 9, 10, 16982 }
	end
end
do
	local player = players["cronxx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9727, 23, 27, 15806 }
	end
end
do
	local player = players["sàlzig"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8927, 67, 103, 14075 }
	end
end
do
	local player = players["ebruzar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9148, 57, 82, 14401 }
	end
end
do
	local player = players["stabbij"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9033, 62, 93, 14224 }
	end
end
do
	local player = players["garøná"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8667, 79, 128, 13602 }
	end
end
do
	local player = players["zyvara"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5092, 294, 473, 9240 }
	end
end
do
	local player = players["falinrog"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9790, 17, 21, 15999 }
	end
end
do
	local player = players["kampfrobbe"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6462, 208, 361, 10804 }
	end
end
do
	local player = players["fenxx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8906, 69, 105, 14051 }
	end
end
do
	local player = players["chokonosuke"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9506, 35, 48, 15328 }
	end
end
do
	local player = players["shïvax"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9253, 53, 72, 14667 }
	end
end
do
	local player = players["no"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9621, 28, 37, 15502 }
	end
end
do
	local player = players["elementherr"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9892, 7, 8, 17390 }
	end
end
do
	local player = players["airlementar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9661, 16, 24, 15353 }
	end
end
do
	local player = players["fenerica"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9615, 18, 27, 15297 }
	end
end
do
	local player = players["vatala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9638, 17, 25, 15342 }
	end
end
do
	local player = players["havannah"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1454, 335, 436, 3 }
	end
end
do
	local player = players["dàblè"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8779, 58, 80, 12422 }
	end
end
do
	local player = players["shamgoth"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9784, 11, 15, 16430 }
	end
end
do
	local player = players["rackbeatz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 10000, 1, 1, 20360 }
	end
end
do
	local player = players["roxxar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9876, 8, 9, 17236 }
	end
end
do
	local player = players["novishok"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9548, 21, 33, 14585 }
	end
end
do
	local player = players["mamablake"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6074, 188, 255, 8748 }
	end
end
do
	local player = players["tripolar"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8900, 45, 57, 1267 }
	end
end
do
	local player = players["fagoth"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9985, 2, 2, 19195 }
	end
end
do
	local player = players["rücknkratzer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3941, 200, 308, 7654 }
	end
end
do
	local player = players["elelelele"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9938, 4, 5, 18335 }
	end
end
do
	local player = players["hundekörperx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9011, 48, 65, 13188 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8782, 50, 63, 1214 }
	end
end
do
	local player = players["elemanlost"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9706, 14, 21, 15577 }
	end
end
do
	local player = players["slawo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7697, 103, 150, 10393 }
	end
end
do
	local player = players["slawiso"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9289, 33, 47, 13820 }
	end
end
do
	local player = players["bolgrash"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 10000, 1, 1, 19422 }
	end
end
do
	local player = players["niphelasthoo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9767, 8, 12, 14402 }
	end
end
do
	local player = players["blitzerina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9622, 12, 19, 14014 }
	end
end
do
	local player = players["lildeep"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5847, 124, 197, 9560 }
	end
end
do
	local player = players["groggii"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9794, 7, 11, 14439 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9961, 3, 3, 4575 }
	end
end
do
	local player = players["rhâjin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9244, 23, 39, 12935 }
	end
end
do
	local player = players["kirïshock"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4263, 177, 272, 8279 }
	end
end
do
	local player = players["zyschomike"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3933, 202, 311, 7638 }
	end
end
do
	local player = players["öhoernchen"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9717, 12, 17, 2133 }
	end
end
do
	local player = players["nichtnude"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9958, 3, 3, 17220 }
	end
end
do
	local player = players["thepeaz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8316, 50, 85, 11840 }
	end
end
do
	local player = players["xiballba"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9038, 29, 50, 12685 }
	end
end
do
	local player = players["totemticker"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9570, 20, 31, 15050 }
	end
end
do
	local player = players["alysida"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9769, 10, 15, 2229 }
	end
end
do
	local player = players["klonadirk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4002, 194, 299, 7773 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9512, 20, 26, 1892 }
	end
end
do
	local player = players["bud"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8454, 71, 101, 11843 }
	end
end
do
	local player = players["shamyna"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9312, 30, 36, 1544 }
	end
end
do
	local player = players["rêgi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9882, 6, 7, 2692 }
	end
end
do
	local player = players["bïolord"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8083, 87, 125, 10981 }
	end
end
do
	local player = players["kortosk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8179, 54, 94, 11526 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3959, 236, 315, 13 }
	end
end
do
	local player = players["drinadia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2391, 297, 394, 6 }
	end
end
do
	local player = players["dèft"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9729, 13, 20, 15643 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4242, 225, 304, 15 }
	end
end
do
	local player = players["nomörser"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8802, 49, 62, 1222 }
	end
end
do
	local player = players["thorák"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6213, 180, 246, 8844 }
	end
end
do
	local player = players["unfallele"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7984, 76, 99, 654 }
	end
end
do
	local player = players["draintrainx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4859, 201, 274, 21 }
	end
end
do
	local player = players["kalystra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4807, 203, 277, 19 }
	end
end
do
	local player = players["orkkultist"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8605, 57, 72, 1136 }
	end
end
do
	local player = players["kreditfalle"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6862, 147, 204, 9425 }
	end
end
do
	local player = players["graugdasch"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8522, 44, 73, 12031 }
	end
end
do
	local player = players["tidemeup"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7892, 83, 109, 637 }
	end
end
do
	local player = players["castalgo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7620, 107, 155, 10328 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9332, 29, 35, 1558 }
	end
end
do
	local player = players["kyde"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8919, 44, 56, 1275 }
	end
end
do
	local player = players["æsma"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5116, 191, 260, 25 }
	end
end
do
	local player = players["eargasm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9936, 4, 4, 16888 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7780, 88, 114, 396 }
	end
end
do
	local player = players["debugmode"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9273, 32, 38, 1526 }
	end
end
do
	local player = players["kettenhailor"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6719, 129, 168, 81 }
	end
end
do
	local player = players["sicknatûre"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7250, 111, 141, 177 }
	end
end
do
	local player = players["kurulón"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3599, 250, 333, 11 }
	end
end
do
	local player = players["krimar"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8998, 41, 52, 1332 }
	end
end
do
	local player = players["tiefighter"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9829, 9, 10, 15488 }
	end
end
do
	local player = players["lontôx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 10000, 1, 1, 17138 }
	end
end
do
	local player = players["verhexenix"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9505, 22, 27, 14431 }
	end
end
do
	local player = players["solutiøn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7778, 103, 170, 10309 }
	end
end
do
	local player = players["hexenbrudi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9067, 37, 50, 13111 }
	end
end
do
	local player = players["afflibrudi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6019, 144, 210, 8451 }
	end
end
do
	local player = players["twiggz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9562, 21, 24, 14569 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9986, 2, 2, 16218 }
	end
end
do
	local player = players["shelldoori"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8453, 72, 127, 11114 }
	end
end
do
	local player = players["umlocken"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9448, 25, 30, 14212 }
	end
end
do
	local player = players["gajanâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3140, 411, 631, 5139 }
	end
end
do
	local player = players["fistrex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9733, 14, 15, 14991 }
	end
end
do
	local player = players["solu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9924, 5, 5, 15865 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9861, 8, 11, 15437 }
	end
end
do
	local player = players["vedmayaga"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 10000, 1, 1, 16364 }
	end
end
do
	local player = players["wasfürsaft"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9676, 16, 18, 14849 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9608, 19, 35, 14020 }
	end
end
do
	local player = players["nupogodi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9972, 3, 3, 16079 }
	end
end
do
	local player = players["solutioñ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9944, 5, 5, 15864 }
	end
end
do
	local player = players["veigãr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5160, 235, 348, 8207 }
	end
end
do
	local player = players["solutíon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9619, 18, 21, 14681 }
	end
end
do
	local player = players["tand"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9124, 35, 47, 13223 }
	end
end
do
	local player = players["abstrus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8235, 82, 145, 10669 }
	end
end
do
	local player = players["avie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9958, 4, 4, 16015 }
	end
end
do
	local player = players["bruderdämo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9281, 34, 55, 13338 }
	end
end
do
	local player = players["lasziv"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8152, 66, 98, 10945 }
	end
end
do
	local player = players["crizzlêê"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8126, 87, 151, 10578 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7742, 22, 38, 8658 }
	end
end
do
	local player = players["madenreich"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9752, 13, 14, 15026 }
	end
end
do
	local player = players["gebrechreiz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9410, 26, 32, 14178 }
	end
end
do
	local player = players["acidbrain"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9129, 41, 71, 12619 }
	end
end
do
	local player = players["dvakira"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9542, 22, 39, 13899 }
	end
end
do
	local player = players["vkaugenguide"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9630, 18, 34, 14053 }
	end
end
do
	local player = players["myrakia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8736, 59, 110, 11562 }
	end
end
do
	local player = players["bomberbombi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9930, 6, 6, 15718 }
	end
end
do
	local player = players["acroorc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9673, 16, 27, 14394 }
	end
end
do
	local player = players["wýrd"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9651, 17, 33, 14143 }
	end
end
do
	local player = players["demonrusko"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9486, 23, 28, 14418 }
	end
end
do
	local player = players["æxecute"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9902, 7, 8, 15503 }
	end
end
do
	local player = players["kotzreiz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9790, 11, 12, 15142 }
	end
end
do
	local player = players["brálock"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 4336, 297, 438, 7095 }
	end
end
do
	local player = players["kronxx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9936, 2, 2, 14321 }
	end
end
do
	local player = players["qronxx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9886, 6, 7, 15713 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 10000, 1, 1, 14598 }
	end
end
do
	local player = players["xadun"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9140, 9, 17, 10608 }
	end
end
do
	local player = players["tinykirï"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6344, 35, 62, 7512 }
	end
end
do
	local player = players["rumgekekt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 10000, 1, 1, 14319 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5972, 413, 641, 9754 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9563, 10, 17, 4582 }
	end
end
do
	local player = players["spielsüchtig"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9967, 6, 6, 18727 }
	end
end
do
	local player = players["ragecriter"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9855, 22, 24, 17806 }
	end
end
do
	local player = players["axteri"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3190, 755, 1210, 6603 }
	end
end
do
	local player = players["grósh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9956, 8, 8, 18513 }
	end
end
do
	local player = players["vodermiene"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9641, 50, 58, 16683 }
	end
end
do
	local player = players["àir"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8999, 118, 160, 14944 }
	end
end
do
	local player = players["elitistjerk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8288, 174, 273, 13041 }
	end
end
do
	local player = players["sweatlord"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8647, 143, 216, 14014 }
	end
end
do
	local player = players["axterin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8936, 123, 170, 14836 }
	end
end
do
	local player = players["sharlera"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9880, 19, 20, 17930 }
	end
end
do
	local player = players["pykê"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9912, 15, 15, 18120 }
	end
end
do
	local player = players["bakihanma"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 10000, 1, 1, 20696 }
	end
end
do
	local player = players["iordhengzt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9994, 2, 2, 20003 }
	end
end
do
	local player = players["safthengst"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9509, 64, 79, 16310 }
	end
end
do
	local player = players["yunobigboi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9962, 7, 7, 18596 }
	end
end
do
	local player = players["silvari"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9541, 60, 74, 16368 }
	end
end
do
	local player = players["fazon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9169, 104, 133, 15408 }
	end
end
do
	local player = players["bommelboris"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9736, 39, 43, 17206 }
	end
end
do
	local player = players["gartenhouse"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8559, 150, 230, 13712 }
	end
end
do
	local player = players["cleaverbruch"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9841, 23, 25, 17778 }
	end
end
do
	local player = players["valnira"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9844, 23, 25, 17778 }
	end
end
do
	local player = players["zapfmischung"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9698, 43, 49, 16887 }
	end
end
do
	local player = players["skillistlava"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9566, 57, 70, 16437 }
	end
end
do
	local player = players["discharged"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9452, 72, 88, 16168 }
	end
end
do
	local player = players["khezan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9817, 27, 30, 17598 }
	end
end
do
	local player = players["kakofonie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9761, 35, 39, 17345 }
	end
end
do
	local player = players["samoi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8980, 119, 163, 14920 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7524, 52, 71, 3242 }
	end
end
do
	local player = players["crìxus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9899, 17, 17, 18039 }
	end
end
do
	local player = players["sitama"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9490, 67, 82, 16274 }
	end
end
do
	local player = players["vimax"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5230, 495, 759, 9095 }
	end
end
do
	local player = players["gróshqt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8030, 200, 314, 12446 }
	end
end
do
	local player = players["nupagadi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9918, 14, 14, 18127 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9612, 9, 15, 4927 }
	end
end
do
	local player = players["kattafury"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9987, 3, 3, 19697 }
	end
end
do
	local player = players["eisenkreuz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9773, 33, 37, 17404 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 10000, 1, 1, 8618 }
	end
end
do
	local player = players["radlader"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9951, 2, 4, 6485 }
	end
end
do
	local player = players["bukephalos"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9792, 31, 34, 17458 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
