-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "togc"
local chunkStartIndex = 8492
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["búlma"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 599, 190, 816, 1004 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4943, 226, 717, 9689 }
	end
end
do
	local player = players["gútdiese"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1027, 183, 772, 1719 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3310, 314, 1192, 6488 }
	end
end
do
	local player = players["êlísâ"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6933, 88, 251, 2773 }
	end
end
do
	local player = players["janette"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8294, 49, 140, 3470 }
	end
end
do
	local player = players["geborkt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5488, 190, 561, 10469 }
	end
end
do
	local player = players["ubøngø"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1607, 172, 685, 1878 }
	end
end
do
	local player = players["jibbitjonny"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2405, 164, 620, 1962 }
	end
end
do
	local player = players["flightbull"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1037, 182, 767, 1736 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2828, 320, 1231, 5543 }
	end
end
do
	local player = players["twingoingo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6467, 42, 107, 10318 }
	end
end
do
	local player = players["makim"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5197, 65, 178, 8689 }
	end
end
do
	local player = players["rotzalgin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3678, 309, 1162, 7209 }
	end
end
do
	local player = players["daddydeath"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7083, 142, 363, 11682 }
	end
end
do
	local player = players["maluna"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4511, 262, 901, 8841 }
	end
end
do
	local player = players["kenpadchi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8928, 66, 134, 14125 }
	end
end
do
	local player = players["clairerouge"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4906, 230, 733, 9616 }
	end
end
do
	local player = players["saltsick"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5274, 199, 588, 10336 }
	end
end
do
	local player = players["jakekim"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8872, 70, 141, 13956 }
	end
end
do
	local player = players["kunkka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1386, 324, 1241, 2717 }
	end
end
do
	local player = players["mích"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2957, 158, 575, 2012 }
	end
end
do
	local player = players["todesritter"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3676, 310, 1163, 7206 }
	end
end
do
	local player = players["zwanny"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3787, 304, 1137, 7422 }
	end
end
do
	local player = players["thønder"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5391, 197, 573, 10401 }
	end
end
do
	local player = players["sherryice"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5963, 178, 502, 10792 }
	end
end
do
	local player = players["palcon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7485, 76, 206, 2938 }
	end
end
do
	local player = players["lakros"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5800, 51, 127, 9565 }
	end
end
do
	local player = players["gloroxis"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4455, 265, 914, 8733 }
	end
end
do
	local player = players["maktylion"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4179, 282, 1030, 8192 }
	end
end
do
	local player = players["diliy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3591, 292, 1074, 6201 }
	end
end
do
	local player = players["walkingwood"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5093, 227, 755, 8794 }
	end
end
do
	local player = players["zwetschgnbam"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5082, 228, 758, 8775 }
	end
end
do
	local player = players["cordyceps"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5270, 220, 699, 9100 }
	end
end
do
	local player = players["senseles"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6110, 170, 481, 10550 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1111, 89, 202, 0 }
	end
end
do
	local player = players["ximti"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3461, 297, 1096, 5976 }
	end
end
do
	local player = players["dabaaum"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8322, 81, 201, 13192 }
	end
end
do
	local player = players["hellcraft"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3416, 298, 1103, 5899 }
	end
end
do
	local player = players["leule"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8591, 71, 169, 13634 }
	end
end
do
	local player = players["cumarin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5549, 201, 623, 9581 }
	end
end
do
	local player = players["gibb"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3737, 63, 145, 1 }
	end
end
do
	local player = players["lazerliesel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4942, 243, 803, 8533 }
	end
end
do
	local player = players["inscape"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2929, 71, 162, 1 }
	end
end
do
	local player = players["sîinon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4773, 255, 852, 8241 }
	end
end
do
	local player = players["lmperior"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4999, 237, 786, 8632 }
	end
end
do
	local player = players["ashalana"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8943, 58, 127, 14004 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4711, 55, 120, 3 }
	end
end
do
	local player = players["eude"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3822, 108, 303, 6656 }
	end
end
do
	local player = players["twincky"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4009, 288, 996, 6922 }
	end
end
do
	local player = players["cartumandua"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3232, 68, 157, 1 }
	end
end
do
	local player = players["fredda"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1822, 82, 185, 0 }
	end
end
do
	local player = players["zentraxe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6978, 32, 69, 43 }
	end
end
do
	local player = players["vindobona"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6240, 60, 136, 10386 }
	end
end
do
	local player = players["leyrah"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4949, 90, 243, 8617 }
	end
end
do
	local player = players["hanfmuh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4538, 101, 276, 7902 }
	end
end
do
	local player = players["kuschelkatze"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2828, 72, 166, 1 }
	end
end
do
	local player = players["îrre"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2141, 257, 1305, 4288 }
	end
end
do
	local player = players["sheadhot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3449, 231, 1114, 6908 }
	end
end
do
	local player = players["demahu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3781, 214, 1020, 7572 }
	end
end
do
	local player = players["equìnøxx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3149, 243, 1186, 6306 }
	end
end
do
	local player = players["shaunie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6704, 113, 448, 10806 }
	end
end
do
	local player = players["bierforfear"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3280, 238, 1160, 6568 }
	end
end
do
	local player = players["waidwoman"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2643, 254, 1262, 5293 }
	end
end
do
	local player = players["gêzet"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 10000, 1, 1, 18778 }
	end
end
do
	local player = players["paraphimose"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8542, 5, 8, 13578 }
	end
end
do
	local player = players["mussich"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4103, 37, 65, 7337 }
	end
end
do
	local player = players["ketaminkaren"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4762, 315, 1161, 10467 }
	end
end
do
	local player = players["minimusius"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5250, 261, 934, 11541 }
	end
end
do
	local player = players["mface"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3687, 397, 1455, 8105 }
	end
end
do
	local player = players["casx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6245, 197, 604, 13095 }
	end
end
do
	local player = players["angezapft"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3904, 390, 1414, 8582 }
	end
end
do
	local player = players["gufelmage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4115, 362, 1345, 9045 }
	end
end
do
	local player = players["noobí"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7758, 136, 361, 15115 }
	end
end
do
	local player = players["yeveta"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2430, 50, 92, 4345 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8618, 104, 223, 16717 }
	end
end
do
	local player = players["flametorch"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7885, 12, 23, 13229 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5782, 211, 681, 12708 }
	end
end
do
	local player = players["dreißigcm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3283, 412, 1512, 7216 }
	end
end
do
	local player = players["mörlîn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8269, 10, 19, 13553 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7167, 158, 456, 14197 }
	end
end
do
	local player = players["magusti"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5131, 278, 995, 11279 }
	end
end
do
	local player = players["schehr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6339, 192, 589, 13178 }
	end
end
do
	local player = players["tunichtgud"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5726, 217, 710, 12585 }
	end
end
do
	local player = players["didlor"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2206, 51, 94, 3944 }
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5302, 256, 907, 11654 }
	end
end
do
	local player = players["blastermage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3064, 420, 1545, 6735 }
	end
end
do
	local player = players["bôfrost"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2334, 428, 1592, 5131 }
	end
end
do
	local player = players["gôrb"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4821, 311, 1140, 10598 }
	end
end
do
	local player = players["enemenemu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4436, 336, 1257, 9751 }
	end
end
do
	local player = players["kraoz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4935, 299, 1091, 10847 }
	end
end
do
	local player = players["plxmorearmor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3041, 195, 928, 1443 }
	end
end
do
	local player = players["rándomx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4325, 331, 1022, 7796 }
	end
end
do
	local player = players["bengel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 571, 233, 816, 81 }
	end
end
do
	local player = players["varosh"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2692, 194, 601, 166 }
	end
end
do
	local player = players["belyon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2253, 201, 637, 160 }
	end
end
do
	local player = players["wantons"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 918, 217, 748, 130 }
	end
end
do
	local player = players["lightfog"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 694, 230, 803, 98 }
	end
end
do
	local player = players["pikzehn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5180, 155, 643, 3301 }
	end
end
do
	local player = players["vulkyrion"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5280, 239, 626, 9517 }
	end
end
do
	local player = players["surenamba"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4257, 170, 766, 2777 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5402, 224, 575, 9739 }
	end
end
do
	local player = players["yuzi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2417, 205, 1011, 1172 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7656, 119, 291, 11805 }
	end
end
do
	local player = players["lalumi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4264, 169, 765, 2777 }
	end
end
do
	local player = players["sudakiing"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3252, 184, 555, 175 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7518, 130, 308, 11693 }
	end
end
do
	local player = players["bubblebub"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6427, 176, 443, 10455 }
	end
end
do
	local player = players["twtanja"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 1539, 221, 1128, 862 }
	end
end
do
	local player = players["jelandra"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 811, 225, 776, 115 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4599, 314, 932, 8290 }
	end
end
do
	local player = players["scürty"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 999, 215, 740, 134 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5247, 241, 646, 9458 }
	end
end
do
	local player = players["marinca"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3865, 358, 1139, 6968 }
	end
end
do
	local player = players["nótank"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4970, 147, 414, 203 }
	end
end
do
	local player = players["xerilla"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7856, 77, 177, 268 }
	end
end
do
	local player = players["potenteente"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6449, 118, 474, 4072 }
	end
end
do
	local player = players["cheriimoya"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4872, 293, 831, 8782 }
	end
end
do
	local player = players["katassine"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4926, 281, 803, 8881 }
	end
end
do
	local player = players["schmaren"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6884, 102, 416, 4467 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4887, 289, 822, 8810 }
	end
end
do
	local player = players["ethereum"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4632, 167, 716, 3038 }
	end
end
do
	local player = players["petrapains"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6134, 131, 516, 3851 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8149, 97, 230, 12730 }
	end
end
do
	local player = players["colbíe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3148, 376, 1218, 5674 }
	end
end
do
	local player = players["camore"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9289, 45, 89, 14908 }
	end
end
do
	local player = players["ellindur"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8331, 66, 138, 289 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7381, 136, 325, 11525 }
	end
end
do
	local player = players["rándom"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7973, 66, 271, 5571 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4102, 342, 1079, 7394 }
	end
end
do
	local player = players["aragroon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6824, 106, 424, 4414 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4876, 292, 830, 8791 }
	end
end
do
	local player = players["solacy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4424, 325, 989, 7975 }
	end
end
do
	local player = players["katyrockt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4977, 159, 670, 3188 }
	end
end
do
	local player = players["saltyberg"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4821, 297, 857, 8691 }
	end
end
do
	local player = players["protacia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6929, 100, 410, 4490 }
	end
end
do
	local player = players["shuffle"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 768, 227, 792, 109 }
	end
end
do
	local player = players["adikia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2765, 190, 595, 167 }
	end
end
do
	local player = players["pfannâ"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6139, 121, 318, 225 }
	end
end
do
	local player = players["ascelia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3925, 354, 1127, 7076 }
	end
end
do
	local player = players["dracato"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8933, 62, 133, 14183 }
	end
end
do
	local player = players["altmodisch"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 998, 231, 1200, 742 }
	end
end
do
	local player = players["juicyduicy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2795, 163, 478, 71 }
	end
end
do
	local player = players["aaris"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6208, 100, 252, 130 }
	end
end
do
	local player = players["raupyi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8761, 40, 83, 236 }
	end
end
do
	local player = players["discpel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 8353, 50, 110, 202 }
	end
end
do
	local player = players["jarana"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 1677, 52, 130, 27 }
	end
end
do
	local player = players["zuayanyanjin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8645, 11, 22, 318 }
	end
end
do
	local player = players["atomhülle"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3509, 322, 1073, 6878 }
	end
end
do
	local player = players["lumøs"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4640, 234, 697, 9096 }
	end
end
do
	local player = players["lemonangel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4831, 219, 660, 9359 }
	end
end
do
	local player = players["zahzuu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5294, 198, 601, 9772 }
	end
end
do
	local player = players["valíndra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6808, 155, 408, 11095 }
	end
end
do
	local player = players["xaktør"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3997, 282, 896, 7835 }
	end
end
do
	local player = players["fraudünsch"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 9678, 25, 42, 15789 }
	end
end
do
	local player = players["puffbrause"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8903, 8, 18, 505 }
	end
end
do
	local player = players["víolett"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 7674, 69, 155, 174 }
	end
end
do
	local player = players["halfbakéd"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4653, 130, 355, 95 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4657, 232, 692, 9130 }
	end
end
do
	local player = players["hbooz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4436, 247, 749, 8696 }
	end
end
do
	local player = players["lagareth"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3803, 297, 971, 7456 }
	end
end
do
	local player = players["zibala"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5247, 200, 607, 9746 }
	end
end
do
	local player = players["kaleyn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5545, 188, 569, 10007 }
	end
end
do
	local player = players["iretia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 9273, 5, 15, 662 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4588, 237, 710, 8995 }
	end
end
do
	local player = players["marijuanaa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8345, 99, 212, 12562 }
	end
end
do
	local player = players["stíflersmøm"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 2644, 166, 488, 69 }
	end
end
do
	local player = players["michaelflexn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3705, 311, 1007, 7264 }
	end
end
do
	local player = players["discoly"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1390, 182, 571, 28 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4703, 227, 682, 9221 }
	end
end
do
	local player = players["moonligt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6858, 91, 209, 148 }
	end
end
do
	local player = players["atileín"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5290, 38, 74, 103 }
	end
end
do
	local player = players["unantastbar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4532, 133, 363, 95 }
	end
end
do
	local player = players["croolshadow"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7663, 128, 299, 11970 }
	end
end
do
	local player = players["miyoki"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5239, 201, 608, 9745 }
	end
end
do
	local player = players["aelivyn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 9184, 30, 55, 288 }
	end
end
do
	local player = players["slitheres"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4654, 218, 986, 8599 }
	end
end
do
	local player = players["hubbsi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2839, 260, 1227, 5246 }
	end
end
do
	local player = players["veranina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3809, 247, 1180, 7038 }
	end
end
do
	local player = players["esberitoxa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3718, 249, 1188, 6869 }
	end
end
do
	local player = players["fyrra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4446, 229, 1054, 8215 }
	end
end
do
	local player = players["samu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8839, 47, 144, 14388 }
	end
end
do
	local player = players["trancilo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4522, 226, 1029, 8355 }
	end
end
do
	local player = players["muschéll"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 1621, 262, 1232, 2995 }
	end
end
do
	local player = players["hémy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7313, 99, 332, 11618 }
	end
end
do
	local player = players["käptncabs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4985, 196, 823, 9211 }
	end
end
do
	local player = players["rédhawk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4402, 230, 1064, 8133 }
	end
end
do
	local player = players["jou"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4756, 75, 240, 10333 }
	end
end
do
	local player = players["ýui"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8505, 67, 145, 432 }
	end
end
do
	local player = players["lizu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 83, 280, 956, 0 }
	end
end
do
	local player = players["protripz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4537, 82, 261, 9857 }
	end
end
do
	local player = players["pitepan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3333, 208, 643, 29 }
	end
end
do
	local player = players["acroboy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3313, 209, 645, 28 }
	end
end
do
	local player = players["hûschdie"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8681, 61, 128, 519 }
	end
end
do
	local player = players["myomy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2949, 220, 680, 22 }
	end
end
do
	local player = players["twmarko"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3022, 217, 673, 24 }
	end
end
do
	local player = players["kamehltotem"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4377, 88, 275, 9510 }
	end
end
do
	local player = players["avaar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 6872, 46, 123, 13341 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 142, 278, 954, 0 }
	end
end
do
	local player = players["giorgioamani"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5321, 61, 198, 11560 }
	end
end
do
	local player = players["firecall"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 4406, 86, 271, 9573 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 8733, 59, 123, 580 }
	end
end
do
	local player = players["shawama"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 2648, 230, 709, 19 }
	end
end
do
	local player = players["rinko"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 4476, 189, 533, 49 }
	end
end
do
	local player = players["reinweich"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3563, 63, 126, 7331 }
	end
end
do
	local player = players["windsea"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4099, 209, 630, 8031 }
	end
end
do
	local player = players["junkmail"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5178, 142, 397, 10146 }
	end
end
do
	local player = players["libercio"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4484, 179, 530, 8786 }
	end
end
do
	local player = players["shìnobu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3078, 246, 785, 6031 }
	end
end
do
	local player = players["lizclark"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5575, 132, 363, 10402 }
	end
end
do
	local player = players["niarin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8032, 78, 162, 12669 }
	end
end
do
	local player = players["zmspender"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4739, 168, 478, 9286 }
	end
end
do
	local player = players["leewon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3610, 229, 716, 7074 }
	end
end
do
	local player = players["eriwana"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3568, 232, 724, 6990 }
	end
end
do
	local player = players["capsløck"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5442, 137, 372, 10341 }
	end
end
do
	local player = players["afflulu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4500, 177, 525, 8817 }
	end
end
do
	local player = players["syrinâ"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6220, 256, 907, 14196 }
	end
end
do
	local player = players["ehre"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5903, 277, 983, 13682 }
	end
end
do
	local player = players["xéy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3285, 452, 2170, 9047 }
	end
end
do
	local player = players["forseti"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7301, 194, 648, 15658 }
	end
end
do
	local player = players["smâshly"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4743, 325, 1261, 12419 }
	end
end
do
	local player = players["utlaegr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8970, 92, 248, 20241 }
	end
end
do
	local player = players["flavourx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8248, 139, 421, 17839 }
	end
end
do
	local player = players["erkk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 1949, 480, 2392, 5368 }
	end
end
do
	local player = players["fûryo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3534, 426, 2007, 9733 }
	end
end
do
	local player = players["nobbèl"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 2626, 475, 2342, 7233 }
	end
end
do
	local player = players["tschaartsch"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7947, 162, 493, 16957 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6067, 40, 119, 3109 }
	end
end
do
	local player = players["rubio"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 7071, 210, 703, 15366 }
	end
end
do
	local player = players["omfg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3540, 424, 2001, 9750 }
	end
end
do
	local player = players["almapatrem"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6033, 41, 120, 3072 }
	end
end
do
	local player = players["leerôoy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4057, 379, 1601, 11175 }
	end
end
do
	local player = players["juppser"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 7233, 25, 84, 3659 }
	end
end
do
	local player = players["grreat"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 3978, 22, 62, 7423 }
	end
end
do
	local player = players["warrgodxqp"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5915, 12, 30, 10808 }
	end
end
do
	local player = players["gördbänks"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 5319, 300, 1123, 13015 }
	end
end
do
	local player = players["icantankthat"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8561, 122, 346, 18873 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 3433, 60, 198, 702 }
	end
end
do
	local player = players["schmerdie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4518, 336, 1315, 12181 }
	end
end
do
	local player = players["uwusan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 5057, 19, 44, 9438 }
	end
end
do
	local player = players["gutdíese"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3916, 396, 1719, 10786 }
	end
end
do
	local player = players["hopfensaft"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 3473, 432, 2055, 9564 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 1000, 68, 271, 293 }
	end
end
do
	local player = players["broton"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6333, 35, 111, 3228 }
	end
end
do
	local player = players["kappel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8014, 158, 477, 17192 }
	end
end
do
	local player = players["ellywóód"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 6337, 247, 879, 14327 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 5700, 47, 130, 2813 }
	end
end
do
	local player = players["maconer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 8882, 97, 269, 19892 }
		player[9][3] = player[9][3] or {}
			player[9][3][13] = { 6267, 36, 113, 3194 }
	end
end
do
	local player = players["parzival"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][13] = { 4256, 355, 1433, 11721 }
	end
end
do
	local player = players["furykail"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][13] = { 1338, 26, 71, 2496 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
